/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.Model;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;


/**--------------------------------------------------------------------------
 * Sistema Guaxinim                                                         |
 * Descrição: Trabalho TG                                                   |
 * Sistema de inventario feito como conclusão do curso de ADS               |
 * na Fatec de Santana de Parnaiba.                                         |
 * @author Alessandro de Sousa da Silva                                     |
 * Data: 08/03/2020                                                         |
/----------------------------------------------------------------------------
 */

public class frmCadCategoria extends javax.swing.JFrame {

    /**
     * Creates new form frmFornecedor
     */
    public frmCadCategoria() {
        initComponents();
        //Adiciona Icone na barra de titulo
        URL iconeImagem = getClass().getResource("/imagens/63d15fc0193fd496d2484a161652f676.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(iconeImagem);
        this.setIconImage(iconeTitulo);
        //Fim - Adiciona Icone na barra de titulo
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGeral = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldNomeCadCategoria = new javax.swing.JTextField();
        jTextFieldCodigoCadCategoria = new javax.swing.JTextField();
        jTextFieldDescricaoCadCategoria = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBoxStatusCadCategoria = new javax.swing.JComboBox<>();
        jButtonLupaCadCategoria = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanelBotoes = new javax.swing.JPanel();
        jButtonSairCadCategoria = new javax.swing.JButton();
        jButtonProximoCadCategoria = new javax.swing.JButton();
        jButtonExcluirCadCategoria = new javax.swing.JButton();
        jButtonCancelarCadCategoria = new javax.swing.JButton();
        jButtonSalvarCadCategoria = new javax.swing.JButton();
        jButtonAlterarCadCategoria = new javax.swing.JButton();
        jButtonNovoCadCategoria = new javax.swing.JButton();
        jButtonAnteriorCadCategoria = new javax.swing.JButton();
        jLabelImagemFundoTela = new javax.swing.JLabel();
        jPanelBotoes1 = new javax.swing.JPanel();
        jButtonSairCadCategoria1 = new javax.swing.JButton();
        jButtonProximoCadCategoria1 = new javax.swing.JButton();
        jButtonExcluirCadCategoria1 = new javax.swing.JButton();
        jButtonCancelarCadCategoria1 = new javax.swing.JButton();
        jButtonSalvarCadCategoria1 = new javax.swing.JButton();
        jButtonAlterarCadCategoria1 = new javax.swing.JButton();
        jButtonNovoCadCategoria1 = new javax.swing.JButton();
        jButtonAnteriorCadCategoria1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Count++ Inventory - Cadastro Categoria");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanelGeral.setBackground(new java.awt.Color(222, 223, 233));
        jPanelGeral.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelGeral.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Status:");
        jPanelGeral.add(jLabel11);
        jLabel11.setBounds(780, 99, 110, 30);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Descrição:");
        jPanelGeral.add(jLabel12);
        jLabel12.setBounds(30, 139, 120, 30);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("Nome:");
        jPanelGeral.add(jLabel13);
        jLabel13.setBounds(30, 99, 100, 30);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("Código:");
        jPanelGeral.add(jLabel15);
        jLabel15.setBounds(30, 60, 100, 30);
        jPanelGeral.add(jTextFieldNomeCadCategoria);
        jTextFieldNomeCadCategoria.setBounds(130, 100, 570, 30);

        jTextFieldCodigoCadCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoCadCategoriaActionPerformed(evt);
            }
        });
        jPanelGeral.add(jTextFieldCodigoCadCategoria);
        jTextFieldCodigoCadCategoria.setBounds(130, 60, 120, 30);

        jTextFieldDescricaoCadCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescricaoCadCategoriaActionPerformed(evt);
            }
        });
        jPanelGeral.add(jTextFieldDescricaoCadCategoria);
        jTextFieldDescricaoCadCategoria.setBounds(130, 140, 910, 30);

        jButton1.setText("jButton1");
        jPanelGeral.add(jButton1);
        jButton1.setBounds(430, 270, 77, 32);

        jComboBoxStatusCadCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha a Opção...", "Ativo", "Inativo", "Pausado" }));
        jPanelGeral.add(jComboBoxStatusCadCategoria);
        jComboBoxStatusCadCategoria.setBounds(850, 100, 190, 30);

        jButtonLupaCadCategoria.setBackground(new java.awt.Color(222, 223, 233));
        jButtonLupaCadCategoria.setForeground(new java.awt.Color(222, 223, 233));
        jButtonLupaCadCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconLupaPesquisa.png"))); // NOI18N
        jButtonLupaCadCategoria.setToolTipText("Clique aqui para fazer a consulta da Categoria.");
        jButtonLupaCadCategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonLupaCadCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLupaCadCategoriaActionPerformed(evt);
            }
        });
        jPanelGeral.add(jButtonLupaCadCategoria);
        jButtonLupaCadCategoria.setBounds(700, 100, 30, 30);

        jLabel1.setFont(new java.awt.Font("BatmanForeverAlternate", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Categoria");
        jPanelGeral.add(jLabel1);
        jLabel1.setBounds(0, 20, 1060, 25);

        getContentPane().add(jPanelGeral);
        jPanelGeral.setBounds(20, 20, 1060, 190);

        jPanelBotoes.setBackground(new java.awt.Color(222, 223, 233));
        jPanelBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonSairCadCategoria.setText("Voltar");
        jButtonSairCadCategoria.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonSairCadCategoria.setMinimumSize(new java.awt.Dimension(82, 26));
        jButtonSairCadCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairCadCategoriaActionPerformed(evt);
            }
        });

        jButtonProximoCadCategoria.setText("Proximo");

        jButtonExcluirCadCategoria.setText("Excluir");
        jButtonExcluirCadCategoria.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonExcluirCadCategoria.setMinimumSize(new java.awt.Dimension(82, 26));

        jButtonCancelarCadCategoria.setText("Cancelar");
        jButtonCancelarCadCategoria.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonCancelarCadCategoria.setMinimumSize(new java.awt.Dimension(82, 26));

        jButtonSalvarCadCategoria.setText("Salvar");
        jButtonSalvarCadCategoria.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonSalvarCadCategoria.setMinimumSize(new java.awt.Dimension(82, 26));

        jButtonAlterarCadCategoria.setText("Alterar");
        jButtonAlterarCadCategoria.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonAlterarCadCategoria.setMinimumSize(new java.awt.Dimension(82, 26));

        jButtonNovoCadCategoria.setText("Novo");
        jButtonNovoCadCategoria.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonNovoCadCategoria.setMinimumSize(new java.awt.Dimension(82, 26));
        jButtonNovoCadCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoCadCategoriaActionPerformed(evt);
            }
        });

        jButtonAnteriorCadCategoria.setText("Anterior");
        jButtonAnteriorCadCategoria.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonAnteriorCadCategoria.setMinimumSize(new java.awt.Dimension(82, 26));

        javax.swing.GroupLayout jPanelBotoesLayout = new javax.swing.GroupLayout(jPanelBotoes);
        jPanelBotoes.setLayout(jPanelBotoesLayout);
        jPanelBotoesLayout.setHorizontalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAnteriorCadCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButtonNovoCadCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButtonAlterarCadCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButtonSalvarCadCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButtonCancelarCadCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButtonExcluirCadCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButtonProximoCadCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 339, Short.MAX_VALUE)
                .addComponent(jButtonSairCadCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelBotoesLayout.setVerticalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonAnteriorCadCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonNovoCadCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAlterarCadCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSalvarCadCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCancelarCadCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonExcluirCadCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonProximoCadCategoria))
                    .addComponent(jButtonSairCadCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanelBotoes);
        jPanelBotoes.setBounds(20, 510, 1060, 50);

        jLabelImagemFundoTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/areadeTrabalhoJanelas.png"))); // NOI18N
        getContentPane().add(jLabelImagemFundoTela);
        jLabelImagemFundoTela.setBounds(0, -10, 1100, 590);

        jPanelBotoes1.setBackground(new java.awt.Color(206, 197, 197));
        jPanelBotoes1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonSairCadCategoria1.setText("Voltar");
        jButtonSairCadCategoria1.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonSairCadCategoria1.setMinimumSize(new java.awt.Dimension(82, 26));
        jButtonSairCadCategoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairCadCategoria1ActionPerformed(evt);
            }
        });

        jButtonProximoCadCategoria1.setText("Proximo");

        jButtonExcluirCadCategoria1.setText("Excluir");
        jButtonExcluirCadCategoria1.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonExcluirCadCategoria1.setMinimumSize(new java.awt.Dimension(82, 26));

        jButtonCancelarCadCategoria1.setText("Cancelar");
        jButtonCancelarCadCategoria1.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonCancelarCadCategoria1.setMinimumSize(new java.awt.Dimension(82, 26));

        jButtonSalvarCadCategoria1.setText("Salvar");
        jButtonSalvarCadCategoria1.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonSalvarCadCategoria1.setMinimumSize(new java.awt.Dimension(82, 26));

        jButtonAlterarCadCategoria1.setText("Alterar");
        jButtonAlterarCadCategoria1.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonAlterarCadCategoria1.setMinimumSize(new java.awt.Dimension(82, 26));

        jButtonNovoCadCategoria1.setText("Novo");
        jButtonNovoCadCategoria1.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonNovoCadCategoria1.setMinimumSize(new java.awt.Dimension(82, 26));
        jButtonNovoCadCategoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoCadCategoria1ActionPerformed(evt);
            }
        });

        jButtonAnteriorCadCategoria1.setText("Anterior");
        jButtonAnteriorCadCategoria1.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonAnteriorCadCategoria1.setMinimumSize(new java.awt.Dimension(82, 26));

        javax.swing.GroupLayout jPanelBotoes1Layout = new javax.swing.GroupLayout(jPanelBotoes1);
        jPanelBotoes1.setLayout(jPanelBotoes1Layout);
        jPanelBotoes1Layout.setHorizontalGroup(
            jPanelBotoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotoes1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAnteriorCadCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButtonNovoCadCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButtonAlterarCadCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButtonSalvarCadCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButtonCancelarCadCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButtonExcluirCadCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButtonProximoCadCategoria1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 339, Short.MAX_VALUE)
                .addComponent(jButtonSairCadCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelBotoes1Layout.setVerticalGroup(
            jPanelBotoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotoes1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBotoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBotoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonAnteriorCadCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonNovoCadCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAlterarCadCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSalvarCadCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCancelarCadCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonExcluirCadCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonProximoCadCategoria1))
                    .addComponent(jButtonSairCadCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanelBotoes1);
        jPanelBotoes1.setBounds(20, 510, 1060, 50);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(100, 240, 0, 0);

        jFormattedTextField1.setText("jFormattedTextField1");
        getContentPane().add(jFormattedTextField1);
        jFormattedTextField1.setBounds(380, 290, 119, 20);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(540, 200, 40, 147);

        setBounds(220, 80, 1096, 579);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodigoCadCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoCadCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoCadCategoriaActionPerformed

    private void jTextFieldDescricaoCadCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoCadCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescricaoCadCategoriaActionPerformed

    private void jButtonSairCadCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairCadCategoriaActionPerformed
        // TODO add your handling code here:
        this.dispose(); //fecha somente o jFrame do frmCadUsuario
         
    }//GEN-LAST:event_jButtonSairCadCategoriaActionPerformed

    private void jButtonNovoCadCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoCadCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNovoCadCategoriaActionPerformed

    private void jButtonLupaCadCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLupaCadCategoriaActionPerformed
        // TODO add your handling code here:
        frmConsultaCadCategoria ConsultaCadCategoria = new frmConsultaCadCategoria();
        ConsultaCadCategoria.setVisible(true);
    }//GEN-LAST:event_jButtonLupaCadCategoriaActionPerformed

    private void jButtonSairCadCategoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairCadCategoria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSairCadCategoria1ActionPerformed

    private void jButtonNovoCadCategoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoCadCategoria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNovoCadCategoria1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCadCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCadCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCadCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCadCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCadCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAlterarCadCategoria;
    private javax.swing.JButton jButtonAlterarCadCategoria1;
    private javax.swing.JButton jButtonAnteriorCadCategoria;
    private javax.swing.JButton jButtonAnteriorCadCategoria1;
    private javax.swing.JButton jButtonCancelarCadCategoria;
    private javax.swing.JButton jButtonCancelarCadCategoria1;
    private javax.swing.JButton jButtonExcluirCadCategoria;
    private javax.swing.JButton jButtonExcluirCadCategoria1;
    private javax.swing.JButton jButtonLupaCadCategoria;
    private javax.swing.JButton jButtonNovoCadCategoria;
    private javax.swing.JButton jButtonNovoCadCategoria1;
    private javax.swing.JButton jButtonProximoCadCategoria;
    private javax.swing.JButton jButtonProximoCadCategoria1;
    private javax.swing.JButton jButtonSairCadCategoria;
    private javax.swing.JButton jButtonSairCadCategoria1;
    private javax.swing.JButton jButtonSalvarCadCategoria;
    private javax.swing.JButton jButtonSalvarCadCategoria1;
    private javax.swing.JComboBox<String> jComboBoxStatusCadCategoria;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabelImagemFundoTela;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JPanel jPanelBotoes1;
    private javax.swing.JPanel jPanelGeral;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCodigoCadCategoria;
    private javax.swing.JTextField jTextFieldDescricaoCadCategoria;
    private javax.swing.JTextField jTextFieldNomeCadCategoria;
    // End of variables declaration//GEN-END:variables
}
