/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.net.URISyntaxException;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**--------------------------------------------------------------------------
 * Sistema Guaxinim                                                         |
 * Descrição: Trabalho TG                                                   |
 * Sistema de inventario feito como conclusão do curso de ADS               |
 * na Fatec de Santana de Parnaiba.                                         |
 * @author Alessandro de Sousa da Silva                                     |
 * Data: 08/03/2020                                                         |
/----------------------------------------------------------------------------
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        //Adiciona Icone na barra de titulo
        URL iconeImagem = getClass().getResource("/imagens/63d15fc0193fd496d2484a161652f676.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(iconeImagem);
        this.setIconImage(iconeTitulo);
        //Fim - Adiciona Icone na barra de titulo
        

    }
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jInternalFrameTelaBemVindos = new javax.swing.JInternalFrame();
        jButtonTelaBoasVindasSair = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelRelatorio1 = new javax.swing.JLabel();
        jButtonRel1 = new javax.swing.JButton();
        jButtonRel2 = new javax.swing.JButton();
        jButtonRel3 = new javax.swing.JButton();
        jButtonRel4 = new javax.swing.JButton();
        jButtonRel5 = new javax.swing.JButton();
        jButtonRel6 = new javax.swing.JButton();
        jButtonRel7 = new javax.swing.JButton();
        jButtonRel8 = new javax.swing.JButton();
        jButtonRel9 = new javax.swing.JButton();
        jButtonCadFornecedor2 = new javax.swing.JButton();
        jButtonCadContreleAcesso1 = new javax.swing.JButton();
        jPanelTelaBVindosCadastro = new javax.swing.JPanel();
        jLabelRelatorio = new javax.swing.JLabel();
        jButtonCadUsuarios1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonCadEndereco1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonCadSenha1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButtonCadProduto1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabelImagemFundoTela = new javax.swing.JLabel();
        jLabelImagemMain = new javax.swing.JLabel();
        jPanelTelaPrincipalRodape = new javax.swing.JPanel();
        jLabelDireitosTelaPrincipal = new javax.swing.JLabel();
        jLData = new javax.swing.JLabel();
        jLHora = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuProdutos = new javax.swing.JMenu();
        jMenuItemCategoria = new javax.swing.JMenuItem();
        jMenuItemTipoProduto = new javax.swing.JMenuItem();
        jMenuItemEndereco = new javax.swing.JMenuItem();
        jMenuItemProdutos = new javax.swing.JMenuItem();
        jMenuItemFornecedor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuUsuarios = new javax.swing.JMenu();
        jMenuItemNivelAcesso = new javax.swing.JMenuItem();
        jMenuItemUsuario = new javax.swing.JMenuItem();
        jMenuItemSenha = new javax.swing.JMenuItem();
        jMenuInventario = new javax.swing.JMenu();
        jMenuItemIniciarInventario = new javax.swing.JMenuItem();
        jMenuItemInventario = new javax.swing.JMenuItem();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuItemRelInventario = new javax.swing.JMenuItem();
        jMenuItemRelProduto = new javax.swing.JMenuItem();
        jMenuItemRelUsuario = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuItemDocumentacao = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSobre = new javax.swing.JMenuItem();
        jMenuItemTelaBemVindo = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuItemTrocarUsuario = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Guaxinim");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jInternalFrameTelaBemVindos.setBorder(null);
        jInternalFrameTelaBemVindos.setForeground(new java.awt.Color(255, 255, 255));
        jInternalFrameTelaBemVindos.setTitle("Sistema Guaxinim - Tela Bem-Vindos");
        jInternalFrameTelaBemVindos.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 12)); // NOI18N
        jInternalFrameTelaBemVindos.setVisible(true);
        jInternalFrameTelaBemVindos.getContentPane().setLayout(null);

        jButtonTelaBoasVindasSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exitl.png"))); // NOI18N
        jButtonTelaBoasVindasSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTelaBoasVindasSairActionPerformed(evt);
            }
        });
        jInternalFrameTelaBemVindos.getContentPane().add(jButtonTelaBoasVindasSair);
        jButtonTelaBoasVindasSair.setBounds(1050, 270, 60, 60);

        jLabel5.setText("RELATORIO");
        jInternalFrameTelaBemVindos.getContentPane().add(jLabel5);
        jLabel5.setBounds(500, 120, 70, 16);

        jLabel7.setText("SAIR");
        jInternalFrameTelaBemVindos.getContentPane().add(jLabel7);
        jLabel7.setBounds(1070, 330, 40, 16);

        jLabel8.setText("CONTROLE DE ACESSO");
        jInternalFrameTelaBemVindos.getContentPane().add(jLabel8);
        jLabel8.setBounds(300, 300, 140, 16);

        jLabel9.setText("FORNECEDORES");
        jInternalFrameTelaBemVindos.getContentPane().add(jLabel9);
        jLabel9.setBounds(320, 150, 110, 16);

        jLabel10.setText("RELATORIO");
        jInternalFrameTelaBemVindos.getContentPane().add(jLabel10);
        jLabel10.setBounds(590, 290, 70, 20);

        jLabel11.setText("RELATORIO");
        jInternalFrameTelaBemVindos.getContentPane().add(jLabel11);
        jLabel11.setBounds(680, 290, 70, 20);

        jLabel12.setText("RELATORIO");
        jInternalFrameTelaBemVindos.getContentPane().add(jLabel12);
        jLabel12.setBounds(500, 200, 70, 20);

        jLabel13.setText("RELATORIO");
        jInternalFrameTelaBemVindos.getContentPane().add(jLabel13);
        jLabel13.setBounds(590, 200, 70, 20);

        jLabel14.setText("RELATORIO");
        jInternalFrameTelaBemVindos.getContentPane().add(jLabel14);
        jLabel14.setBounds(680, 200, 70, 20);

        jLabel15.setText("RELATORIO");
        jInternalFrameTelaBemVindos.getContentPane().add(jLabel15);
        jLabel15.setBounds(590, 120, 70, 20);

        jLabel16.setText("RELATORIO");
        jInternalFrameTelaBemVindos.getContentPane().add(jLabel16);
        jLabel16.setBounds(680, 120, 70, 20);

        jLabel17.setText("RELATORIO");
        jInternalFrameTelaBemVindos.getContentPane().add(jLabel17);
        jLabel17.setBounds(510, 290, 70, 20);

        jLabelRelatorio1.setFont(new java.awt.Font("Doppio One", 1, 18)); // NOI18N
        jLabelRelatorio1.setText("RELATORIOS");
        jInternalFrameTelaBemVindos.getContentPane().add(jLabelRelatorio1);
        jLabelRelatorio1.setBounds(570, 20, 130, 24);

        jButtonRel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio.png"))); // NOI18N
        jButtonRel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRel1ActionPerformed(evt);
            }
        });
        jInternalFrameTelaBemVindos.getContentPane().add(jButtonRel1);
        jButtonRel1.setBounds(510, 60, 50, 60);

        jButtonRel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio.png"))); // NOI18N
        jButtonRel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRel2ActionPerformed(evt);
            }
        });
        jInternalFrameTelaBemVindos.getContentPane().add(jButtonRel2);
        jButtonRel2.setBounds(510, 230, 50, 60);

        jButtonRel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio.png"))); // NOI18N
        jButtonRel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRel3ActionPerformed(evt);
            }
        });
        jInternalFrameTelaBemVindos.getContentPane().add(jButtonRel3);
        jButtonRel3.setBounds(600, 60, 50, 60);

        jButtonRel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio.png"))); // NOI18N
        jButtonRel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRel4ActionPerformed(evt);
            }
        });
        jInternalFrameTelaBemVindos.getContentPane().add(jButtonRel4);
        jButtonRel4.setBounds(690, 60, 50, 60);

        jButtonRel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio.png"))); // NOI18N
        jButtonRel5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRel5ActionPerformed(evt);
            }
        });
        jInternalFrameTelaBemVindos.getContentPane().add(jButtonRel5);
        jButtonRel5.setBounds(600, 140, 50, 60);

        jButtonRel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio.png"))); // NOI18N
        jButtonRel6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRel6ActionPerformed(evt);
            }
        });
        jInternalFrameTelaBemVindos.getContentPane().add(jButtonRel6);
        jButtonRel6.setBounds(690, 140, 50, 60);

        jButtonRel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio.png"))); // NOI18N
        jButtonRel7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRel7ActionPerformed(evt);
            }
        });
        jInternalFrameTelaBemVindos.getContentPane().add(jButtonRel7);
        jButtonRel7.setBounds(600, 230, 50, 60);

        jButtonRel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio.png"))); // NOI18N
        jButtonRel8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRel8ActionPerformed(evt);
            }
        });
        jInternalFrameTelaBemVindos.getContentPane().add(jButtonRel8);
        jButtonRel8.setBounds(690, 230, 50, 60);

        jButtonRel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio.png"))); // NOI18N
        jButtonRel9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRel9ActionPerformed(evt);
            }
        });
        jInternalFrameTelaBemVindos.getContentPane().add(jButtonRel9);
        jButtonRel9.setBounds(510, 140, 50, 60);

        jButtonCadFornecedor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fornecedor.png"))); // NOI18N
        jButtonCadFornecedor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadFornecedor2ActionPerformed(evt);
            }
        });
        jInternalFrameTelaBemVindos.getContentPane().add(jButtonCadFornecedor2);
        jButtonCadFornecedor2.setBounds(320, 60, 90, 90);

        jButtonCadContreleAcesso1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/controleAcesso112.png"))); // NOI18N
        jButtonCadContreleAcesso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadContreleAcesso1ActionPerformed(evt);
            }
        });
        jInternalFrameTelaBemVindos.getContentPane().add(jButtonCadContreleAcesso1);
        jButtonCadContreleAcesso1.setBounds(320, 210, 90, 90);

        jPanelTelaBVindosCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CADASTROS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanelTelaBVindosCadastro.setLayout(null);

        jLabelRelatorio.setFont(new java.awt.Font("Doppio One", 1, 18)); // NOI18N
        jLabelRelatorio.setText("CADASTROS");
        jPanelTelaBVindosCadastro.add(jLabelRelatorio);
        jLabelRelatorio.setBounds(170, 0, 130, 24);

        jButtonCadUsuarios1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Usuario.jpg"))); // NOI18N
        jButtonCadUsuarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadUsuarios1ActionPerformed(evt);
            }
        });
        jPanelTelaBVindosCadastro.add(jButtonCadUsuarios1);
        jButtonCadUsuarios1.setBounds(30, 40, 90, 90);

        jLabel3.setText("  USUARIOS");
        jPanelTelaBVindosCadastro.add(jLabel3);
        jLabel3.setBounds(40, 130, 70, 16);

        jButtonCadEndereco1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/endereços.png"))); // NOI18N
        jButtonCadEndereco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadEndereco1ActionPerformed(evt);
            }
        });
        jPanelTelaBVindosCadastro.add(jButtonCadEndereco1);
        jButtonCadEndereco1.setBounds(30, 190, 90, 90);

        jLabel2.setText("ENDEREÇOS");
        jPanelTelaBVindosCadastro.add(jLabel2);
        jLabel2.setBounds(40, 280, 80, 16);

        jButtonCadSenha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/senha3_1.png"))); // NOI18N
        jButtonCadSenha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadSenha1ActionPerformed(evt);
            }
        });
        jPanelTelaBVindosCadastro.add(jButtonCadSenha1);
        jButtonCadSenha1.setBounds(170, 190, 90, 90);

        jLabel6.setText("SENHAS");
        jPanelTelaBVindosCadastro.add(jLabel6);
        jLabel6.setBounds(190, 280, 80, 16);

        jButtonCadProduto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto.png"))); // NOI18N
        jButtonCadProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadProduto1ActionPerformed(evt);
            }
        });
        jPanelTelaBVindosCadastro.add(jButtonCadProduto1);
        jButtonCadProduto1.setBounds(170, 40, 90, 90);

        jLabel4.setText("PRODUTOS");
        jPanelTelaBVindosCadastro.add(jLabel4);
        jLabel4.setBounds(180, 130, 70, 16);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FundoTela bem vindo.jpg"))); // NOI18N
        jLabel19.setText("jLabel19");
        jPanelTelaBVindosCadastro.add(jLabel19);
        jLabel19.setBounds(0, 0, 440, 330);

        jInternalFrameTelaBemVindos.getContentPane().add(jPanelTelaBVindosCadastro);
        jPanelTelaBVindosCadastro.setBounds(10, 20, 440, 320);

        jLabelImagemFundoTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FundoTela bem vindo.jpg"))); // NOI18N
        jInternalFrameTelaBemVindos.getContentPane().add(jLabelImagemFundoTela);
        jLabelImagemFundoTela.setBounds(-190, 0, 1340, 360);

        getContentPane().add(jInternalFrameTelaBemVindos);
        jInternalFrameTelaBemVindos.setBounds(20, 190, 1130, 380);

        jLabelImagemMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/main.jpg"))); // NOI18N
        getContentPane().add(jLabelImagemMain);
        jLabelImagemMain.setBounds(0, 0, 1250, 580);

        jLabelDireitosTelaPrincipal.setFont(new java.awt.Font("Ebrima", 0, 10)); // NOI18N
        jLabelDireitosTelaPrincipal.setText("Sistema Guaxinim versão 2021.0.01 - desenvolvido por alunos do CPS Fatec SdP - ( Adilson, Alessandro, Cristoffer, Davi e Valdilei ) Trabalho do TG - com a orientação do Professor Aimar Martins Lopes                                 ");
        jPanelTelaPrincipalRodape.add(jLabelDireitosTelaPrincipal);

        jLData.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jPanelTelaPrincipalRodape.add(jLData);

        jLHora.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jPanelTelaPrincipalRodape.add(jLHora);

        getContentPane().add(jPanelTelaPrincipalRodape);
        jPanelTelaPrincipalRodape.setBounds(0, 580, 1170, 20);

        jMenuCadastro.setText("Cadastros");

        jMenuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos.png"))); // NOI18N
        jMenuProdutos.setText("Produtos");

        jMenuItemCategoria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/categorias.png"))); // NOI18N
        jMenuItemCategoria.setText("Categoria");
        jMenuItemCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCategoriaActionPerformed(evt);
            }
        });
        jMenuProdutos.add(jMenuItemCategoria);

        jMenuItemTipoProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemTipoProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tiposproduto.png"))); // NOI18N
        jMenuItemTipoProduto.setText("Tipo do Produto");
        jMenuItemTipoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTipoProdutoActionPerformed(evt);
            }
        });
        jMenuProdutos.add(jMenuItemTipoProduto);

        jMenuItemEndereco.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/endereço.png"))); // NOI18N
        jMenuItemEndereco.setText("Endereço");
        jMenuItemEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEnderecoActionPerformed(evt);
            }
        });
        jMenuProdutos.add(jMenuItemEndereco);

        jMenuItemProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos.png"))); // NOI18N
        jMenuItemProdutos.setText("Produto");
        jMenuItemProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdutosActionPerformed(evt);
            }
        });
        jMenuProdutos.add(jMenuItemProdutos);

        jMenuCadastro.add(jMenuProdutos);

        jMenuItemFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fornecedorico.png"))); // NOI18N
        jMenuItemFornecedor.setText("Fornecedor");
        jMenuItemFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFornecedorActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemFornecedor);
        jMenuCadastro.add(jSeparator1);

        jMenuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Senhas1.png"))); // NOI18N
        jMenuUsuarios.setText("Usuarios");

        jMenuItemNivelAcesso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemNivelAcesso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/NivelAcesso.png"))); // NOI18N
        jMenuItemNivelAcesso.setText("Nivel de Acesso");
        jMenuItemNivelAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNivelAcessoActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemNivelAcesso);

        jMenuItemUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Usuarios.jpg"))); // NOI18N
        jMenuItemUsuario.setText("Usuario");
        jMenuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemUsuario);

        jMenuItemSenha.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/senhas2.png"))); // NOI18N
        jMenuItemSenha.setText("Senha");
        jMenuItemSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSenhaActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemSenha);

        jMenuCadastro.add(jMenuUsuarios);

        jMenuBar1.add(jMenuCadastro);

        jMenuInventario.setText("Inventário");

        jMenuItemIniciarInventario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemIniciarInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/inventario2.png"))); // NOI18N
        jMenuItemIniciarInventario.setText("Iniciar Inventario");
        jMenuItemIniciarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIniciarInventarioActionPerformed(evt);
            }
        });
        jMenuInventario.add(jMenuItemIniciarInventario);

        jMenuItemInventario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/inventario.png"))); // NOI18N
        jMenuItemInventario.setText("Inventario");
        jMenuItemInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInventarioActionPerformed(evt);
            }
        });
        jMenuInventario.add(jMenuItemInventario);

        jMenuBar1.add(jMenuInventario);

        jMenuRelatorio.setText("Relatorios");

        jMenuItemRelInventario.setText("Inventario");
        jMenuRelatorio.add(jMenuItemRelInventario);

        jMenuItemRelProduto.setText("Produtos");
        jMenuItemRelProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelProdutoActionPerformed(evt);
            }
        });
        jMenuRelatorio.add(jMenuItemRelProduto);

        jMenuItemRelUsuario.setText("Usuarios");
        jMenuRelatorio.add(jMenuItemRelUsuario);

        jMenuBar1.add(jMenuRelatorio);

        jMenuAjuda.setText("Ajuda");

        jMenuItemDocumentacao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemDocumentacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Documentos.png"))); // NOI18N
        jMenuItemDocumentacao.setText("Documentação");
        jMenuItemDocumentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDocumentacaoActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemDocumentacao);
        jMenuAjuda.add(jSeparator3);

        jMenuItemSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconsobre.png"))); // NOI18N
        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemSobre);

        jMenuItemTelaBemVindo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemTelaBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telapainel.png"))); // NOI18N
        jMenuItemTelaBemVindo.setText("Tela Bem-Vindo");
        jMenuItemTelaBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaBemVindoActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemTelaBemVindo);

        jMenuBar1.add(jMenuAjuda);

        jMenuSair.setText("Sair");

        jMenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/MenuSair.png"))); // NOI18N
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuItemTrocarUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemTrocarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logout.png"))); // NOI18N
        jMenuItemTrocarUsuario.setText("Trocar Usuario");
        jMenuItemTrocarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTrocarUsuarioActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemTrocarUsuario);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1184, 666));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemDocumentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDocumentacaoActionPerformed
       

                   
    }//GEN-LAST:event_jMenuItemDocumentacaoActionPerformed

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        // Chamando tela sobre
        TelaSobre sobre = new TelaSobre();
        sobre.setVisible(true);

    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
        //Programação do botão Sair
        switch (JOptionPane.showConfirmDialog(null,
                "Deseja realmente Sair?",
                "Saindo do Sistema Guaxinim...",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE )) {
            case 0:
                System.out.println("Saindo do Sistema Guaxinim...");
                System.exit(0);
                break;
            case 1:
                System.out.println("Voltando para o Sistema Guaxinim...");
                break;
         //   case 2:
         //       System.out.println("botao cancel clicado");
         //       break;
        }
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jButtonTelaBoasVindasSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTelaBoasVindasSairActionPerformed
        // TODO add your handling code here:
        //Swicth para mensagem de Sair do APP
        switch (JOptionPane.showConfirmDialog(null,
                "Deseja Sair da Tela de Bem Vindos?",
                "Sistema Guaxinim...",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE )) {
            case 0:
                System.out.println("Saindo do Sistema Guaxinim...");
                jInternalFrameTelaBemVindos.dispose();
                break;
            case 1:
                System.out.println("Voltando para o Sistema Guaxinim...");
                break;
         //   case 2:
         //       System.out.println("botao cancel clicado");
         //       break;
        }
        
    }//GEN-LAST:event_jButtonTelaBoasVindasSairActionPerformed

    private void jButtonRel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRel1ActionPerformed

    private void jButtonCadContreleAcesso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadContreleAcesso1ActionPerformed
        // TODO add your handling code here:
        // Chamando tela frmTelaNiveldeAcesso
        frmTelaNiveldeAcesso NiveldeAcesso = new frmTelaNiveldeAcesso();
        NiveldeAcesso.setVisible(true);
    }//GEN-LAST:event_jButtonCadContreleAcesso1ActionPerformed

    private void jButtonCadFornecedor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadFornecedor2ActionPerformed
        // TODO add your handling code here:
         // Chamando tela Cad Fornecedor
        frmCadFornecedor telaFornec = new frmCadFornecedor();
        telaFornec.setVisible(true);
    }//GEN-LAST:event_jButtonCadFornecedor2ActionPerformed

    private void jButtonRel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRel2ActionPerformed

    private void jButtonRel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRel3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRel3ActionPerformed

    private void jButtonRel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRel4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRel4ActionPerformed

    private void jButtonRel5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRel5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRel5ActionPerformed

    private void jButtonRel6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRel6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRel6ActionPerformed

    private void jButtonRel7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRel7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRel7ActionPerformed

    private void jButtonRel8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRel8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRel8ActionPerformed

    private void jButtonRel9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRel9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRel9ActionPerformed

    private void jMenuItemTelaBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaBemVindoActionPerformed
            // Chamando tela Bemvindos
                TelaPrincipal tela = new TelaPrincipal();
                tela.setVisible(true);
                dispose();
        
    }//GEN-LAST:event_jMenuItemTelaBemVindoActionPerformed

    private void jMenuItemTrocarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTrocarUsuarioActionPerformed
        // TODO add your handling code here:
         // Chamando tela principal
        TelaLogin_1 telaLogin = new TelaLogin_1();
        telaLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemTrocarUsuarioActionPerformed

    private void jMenuItemInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInventarioActionPerformed
        // TODO add your handling code here:
        // Chamando tela Inventario
        frmInventario Inventario = new frmInventario();
         Inventario.setVisible(true);
    }//GEN-LAST:event_jMenuItemInventarioActionPerformed

    private void jMenuItemRelProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemRelProdutoActionPerformed

    private void jMenuItemIniciarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIniciarInventarioActionPerformed
        // TODO add your handling code here:
        // Chamando tela Tela Iniciar Inventario
        frmTelaIniciarInventario TelaIniciarInventario = new frmTelaIniciarInventario();
        TelaIniciarInventario.setVisible(true);
    }//GEN-LAST:event_jMenuItemIniciarInventarioActionPerformed

    private void jMenuItemSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSenhaActionPerformed
        // TODO add your handling code here:
        // Chamando tela Cad Categoria
        frmCadTrocaSenha CadTrocaSenha = new frmCadTrocaSenha();
        CadTrocaSenha.setVisible(true);
    }//GEN-LAST:event_jMenuItemSenhaActionPerformed

    private void jMenuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioActionPerformed
        // TODO add your handling code here:
        // Chamando tela Cad Usuario
        frmCadUsuario telaCadUsuario = new frmCadUsuario();
        telaCadUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItemUsuarioActionPerformed

    private void jMenuItemNivelAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNivelAcessoActionPerformed
        // TODO add your handling code here:
        // Chamando tela frmTelaNiveldeAcesso
        frmTelaNiveldeAcesso NiveldeAcesso = new frmTelaNiveldeAcesso();
        NiveldeAcesso.setVisible(true);
    }//GEN-LAST:event_jMenuItemNivelAcessoActionPerformed

    private void jMenuItemFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFornecedorActionPerformed
        // TODO add your handling code here:
        // Chamando tela Cad Fornecedor
        frmCadFornecedor telaFornec = new frmCadFornecedor();
        telaFornec.setVisible(true);
    }//GEN-LAST:event_jMenuItemFornecedorActionPerformed

    private void jMenuItemProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutosActionPerformed
        // TODO add your handling code here:
        // Chamando tela Cad Produto
        frmCadProduto telaProduto = new frmCadProduto();
        telaProduto.setVisible(true);
    }//GEN-LAST:event_jMenuItemProdutosActionPerformed

    private void jMenuItemEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEnderecoActionPerformed
        // TODO add your handling code here:
        // Chamando tela CadEnderecos
        frmCadEnderecos telaCadEnderecos = new frmCadEnderecos();
        telaCadEnderecos.setVisible(true);
    }//GEN-LAST:event_jMenuItemEnderecoActionPerformed

    private void jMenuItemTipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTipoProdutoActionPerformed
        // TODO add your handling code here:
        // Chamando tela Cad Tipo de
        frmTelaTiposdeProduto telaTelaTiposdeProduto = new frmTelaTiposdeProduto();
        telaTelaTiposdeProduto.setVisible(true);
    }//GEN-LAST:event_jMenuItemTipoProdutoActionPerformed

    private void jMenuItemCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCategoriaActionPerformed
        // TODO add your handling code here:
        // Chamando tela Cad Categoria
        frmCadCategoria telaCategoria = new frmCadCategoria();
        telaCategoria.setVisible(true);
    }//GEN-LAST:event_jMenuItemCategoriaActionPerformed

    private void jButtonCadProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadProduto1ActionPerformed
        // TODO add your handling code here:
        // Chamando tela Cad Produto
        frmCadProduto telaProduto = new frmCadProduto();
        telaProduto.setVisible(true);
    }//GEN-LAST:event_jButtonCadProduto1ActionPerformed

    private void jButtonCadSenha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadSenha1ActionPerformed
        // TODO add your handling code here:
        // Chamando tela Cad Categoria
        frmCadTrocaSenha CadTrocaSenha = new frmCadTrocaSenha();
        CadTrocaSenha.setVisible(true);

    }//GEN-LAST:event_jButtonCadSenha1ActionPerformed

    private void jButtonCadEndereco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadEndereco1ActionPerformed
        // TODO add your handling code here:
        // Chamando tela CadEnderecos
        frmCadEnderecos telaCadEnderecos = new frmCadEnderecos();
        telaCadEnderecos.setVisible(true);
    }//GEN-LAST:event_jButtonCadEndereco1ActionPerformed

    private void jButtonCadUsuarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadUsuarios1ActionPerformed
        // TODO add your handling code here:
        // Chamando tela Cad Usuario
        frmCadUsuario telaCadUsuario = new frmCadUsuario();
        telaCadUsuario.setVisible(true);
    }//GEN-LAST:event_jButtonCadUsuarios1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 // Programação para exibir data na jframe
        Date dataSistema = new Date (); 
        SimpleDateFormat formato = new SimpleDateFormat ("dd/MM/yyyy");//SimpleDateFormat é um formato que pega uma data e convert para uma string
        jLData.setText(formato.format(dataSistema));
        
        // Programação para exibir hora na jframe
        Timer timer = new Timer(1000, new hora());
        timer.start();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadContreleAcesso1;
    private javax.swing.JButton jButtonCadEndereco1;
    private javax.swing.JButton jButtonCadFornecedor2;
    private javax.swing.JButton jButtonCadProduto1;
    private javax.swing.JButton jButtonCadSenha1;
    private javax.swing.JButton jButtonCadUsuarios1;
    private javax.swing.JButton jButtonRel1;
    private javax.swing.JButton jButtonRel2;
    private javax.swing.JButton jButtonRel3;
    private javax.swing.JButton jButtonRel4;
    private javax.swing.JButton jButtonRel5;
    private javax.swing.JButton jButtonRel6;
    private javax.swing.JButton jButtonRel7;
    private javax.swing.JButton jButtonRel8;
    private javax.swing.JButton jButtonRel9;
    private javax.swing.JButton jButtonTelaBoasVindasSair;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JInternalFrame jInternalFrameTelaBemVindos;
    private javax.swing.JLabel jLData;
    private javax.swing.JLabel jLHora;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDireitosTelaPrincipal;
    private javax.swing.JLabel jLabelImagemFundoTela;
    private javax.swing.JLabel jLabelImagemMain;
    private javax.swing.JLabel jLabelRelatorio;
    private javax.swing.JLabel jLabelRelatorio1;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuInventario;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemCategoria;
    private javax.swing.JMenuItem jMenuItemDocumentacao;
    private javax.swing.JMenuItem jMenuItemEndereco;
    private javax.swing.JMenuItem jMenuItemFornecedor;
    private javax.swing.JMenuItem jMenuItemIniciarInventario;
    private javax.swing.JMenuItem jMenuItemInventario;
    private javax.swing.JMenuItem jMenuItemNivelAcesso;
    private javax.swing.JMenuItem jMenuItemProdutos;
    private javax.swing.JMenuItem jMenuItemRelInventario;
    private javax.swing.JMenuItem jMenuItemRelProduto;
    private javax.swing.JMenuItem jMenuItemRelUsuario;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemSenha;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenuItem jMenuItemTelaBemVindo;
    private javax.swing.JMenuItem jMenuItemTipoProduto;
    private javax.swing.JMenuItem jMenuItemTrocarUsuario;
    private javax.swing.JMenuItem jMenuItemUsuario;
    private javax.swing.JMenu jMenuProdutos;
    private javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuUsuarios;
    private javax.swing.JPanel jPanelTelaBVindosCadastro;
    private javax.swing.JPanel jPanelTelaPrincipalRodape;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables

class hora implements ActionListener {
    @Override
    public void actionPerformed(ActionEvent e){
        Calendar now = Calendar.getInstance();
        jLHora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
    }//fim da actionPerformed
}//fim da class

}
