package visao;

/**
 *Sistema de Cadastro - Tela Cad Pessoa Fisica
 *Aula de Linguagem de Programação III
 *@author Alessandro de Sousa da Silva
 *@since Criada em 25/03/2021 as 10:00
 */

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *Sistema de Cadastro - Tela Inicial
 *Aula de Linguagem de Programação III
 *@author Alessandro de Sousa da Silva
 *@since Criada em 25/03/2021 as 10:00
 */

public class FramePessoaFisica extends javax.swing.JFrame {
//Cria um objeto do tipo Cliente sem nenhum dado atribuido / Uso do contrutor vazio
Cliente cliente = new Cliente();    
SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy"); //Cria um objeto formatador para a Data de Nascimento

    public FramePessoaFisica() {
        initComponents();
        //Adiciona Icone na barra de titulo
        URL iconeImagem = getClass().getResource("/imagem/iconePrincipal.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(iconeImagem);
        this.setIconImage(iconeTitulo);
        //Fim - Adiciona Icone na barra de titulo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupoSexo = new javax.swing.ButtonGroup();
        jLabelImagemFundoBordaPaineis = new javax.swing.JLabel();
        jPanelCadastroFisica = new javax.swing.JPanel();
        lbEnderecoCad = new javax.swing.JLabel();
        txNomeCad = new javax.swing.JTextField();
        txNomeEnderecoCad = new javax.swing.JTextField();
        lbNomeNomeCad = new javax.swing.JLabel();
        lbDtNascimentoCad = new javax.swing.JLabel();
        lbSexoCad = new javax.swing.JLabel();
        txNomeCidadeCad = new javax.swing.JTextField();
        lbEstadoCad = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        lbCidadeCad = new javax.swing.JLabel();
        jRadioButtonMasculinoCad = new javax.swing.JRadioButton();
        jRadioButtonFemininoCad = new javax.swing.JRadioButton();
        jLabelNumero = new javax.swing.JLabel();
        txNomeNumeroCad = new javax.swing.JTextField();
        jFormattedTextFieldDtNascimento = new javax.swing.JFormattedTextField();
        jLabelCPF = new javax.swing.JLabel();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jlRenda = new javax.swing.JLabel();
        jtRenda = new javax.swing.JTextField();
        jPanelCadastro2 = new javax.swing.JPanel();
        jCheckBoxLeitura = new javax.swing.JCheckBox();
        jCheckBoxFutebol = new javax.swing.JCheckBox();
        jCheckBoxPescaria = new javax.swing.JCheckBox();
        jCheckBoxDanca = new javax.swing.JCheckBox();
        jCheckBoxGames = new javax.swing.JCheckBox();
        jCheckBoxCorrer = new javax.swing.JCheckBox();
        jCheckBoxCozinhar = new javax.swing.JCheckBox();
        jCheckBoxMusica = new javax.swing.JCheckBox();
        jbTituloCad = new javax.swing.JLabel();
        jPanelBotoes = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jLabeImangemFundo = new javax.swing.JLabel();

        jLabelImagemFundoBordaPaineis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/TalaFundoCadPaineis.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FATEC Linguagem de Programação III  - Sistema de Cadastro");
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanelCadastroFisica.setBackground(new java.awt.Color(222, 222, 210));
        jPanelCadastroFisica.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lbEnderecoCad.setText("Endereço:.");

        txNomeCad.setToolTipText("Digite aqui o nome completo");
        txNomeCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNomeCadActionPerformed(evt);
            }
        });

        txNomeEnderecoCad.setToolTipText("Digite aqui o endereço.");
        txNomeEnderecoCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNomeEnderecoCadActionPerformed(evt);
            }
        });

        lbNomeNomeCad.setText("Nome:.");

        lbDtNascimentoCad.setText("Dt. Nascimento:.");

        lbSexoCad.setText("   Sexo:.");

        txNomeCidadeCad.setToolTipText("Digite aqui a cidade, se preferir digite (Bairro / Cidade).");
        txNomeCidadeCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNomeCidadeCadActionPerformed(evt);
            }
        });

        lbEstadoCad.setText("Estado:.");

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "AC - Acre", "AL - Alagoas", "AP - Amapá", "AM - Amazonas", "BA - Bahia ", "CE - Ceará", "DF - Distrito Federal", "ES - Espírito Santo", "GO - Goiás", "MA - Maranhão", "MT - Mato Grosso", "MS - Mato Grosso do Sul", "MG - Minas Gerais", "PA - Pará", "PB - Paraíba", "PR - Paraná", "PE - Pernambuco", "PI - Piauí", "RR - Roraima", "RO - Rondônia", "RJ - Rio de Janeiro", "RN - Rio Grande do Norte", "RS - Rio Grande do Sul", "SC - Santa Catarina", "SP - São Paulo", "SE - Sergipe", "TO - Tocantins" }));
        cbEstado.setToolTipText("Selecione o Estado.");

        lbCidadeCad.setText("Cidade:.");

        buttonGroupoSexo.add(jRadioButtonMasculinoCad);
        jRadioButtonMasculinoCad.setText("Masculino");

        buttonGroupoSexo.add(jRadioButtonFemininoCad);
        jRadioButtonFemininoCad.setText("Feminino");
        jRadioButtonFemininoCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFemininoCadActionPerformed(evt);
            }
        });

        jLabelNumero.setText("Numero:.");

        txNomeNumeroCad.setToolTipText("Digite aqui o Numero do endereço.");
        txNomeNumeroCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNomeNumeroCadActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldDtNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDtNascimento.setToolTipText("Digite aqui a Data de Nascimento sem uso dos caracteres especiais.");

        jLabelCPF.setText("CPF:.");

        try {
            jFormattedTextFieldCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPF.setToolTipText("Digite aqui o numero do CPF sem os pontos.");

        jlRenda.setText("Renda:");

        jtRenda.setToolTipText("Digite aqui o rendimento mensal (ex. Salário).");

        javax.swing.GroupLayout jPanelCadastroFisicaLayout = new javax.swing.GroupLayout(jPanelCadastroFisica);
        jPanelCadastroFisica.setLayout(jPanelCadastroFisicaLayout);
        jPanelCadastroFisicaLayout.setHorizontalGroup(
            jPanelCadastroFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroFisicaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lbNomeNomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(txNomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbDtNascimentoCad)
                .addGap(3, 3, 3)
                .addComponent(jFormattedTextFieldDtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelCadastroFisicaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbEnderecoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(txNomeEnderecoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jLabelNumero)
                .addGap(5, 5, 5)
                .addComponent(txNomeNumeroCad, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelCadastroFisicaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lbCidadeCad, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(txNomeCidadeCad, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jPanelCadastroFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEstadoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCadastroFisicaLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanelCadastroFisicaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbSexoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jRadioButtonMasculinoCad)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonFemininoCad)
                .addGap(19, 19, 19)
                .addComponent(jlRenda)
                .addGap(9, 9, 9)
                .addComponent(jtRenda, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jLabelCPF)
                .addGap(2, 2, 2)
                .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelCadastroFisicaLayout.setVerticalGroup(
            jPanelCadastroFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroFisicaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelCadastroFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txNomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldDtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCadastroFisicaLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanelCadastroFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNomeNomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDtNascimentoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(jPanelCadastroFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txNomeEnderecoCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNomeNumeroCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCadastroFisicaLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanelCadastroFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEnderecoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNumero))))
                .addGap(12, 12, 12)
                .addGroup(jPanelCadastroFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroFisicaLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lbCidadeCad, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadastroFisicaLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txNomeCidadeCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadastroFisicaLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lbEstadoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanelCadastroFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroFisicaLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbSexoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadastroFisicaLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jRadioButtonMasculinoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadastroFisicaLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jRadioButtonFemininoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadastroFisicaLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jlRenda))
                    .addComponent(jtRenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCadastroFisicaLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabelCPF))
                    .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanelCadastroFisica);
        jPanelCadastroFisica.setBounds(0, 40, 830, 200);

        jPanelCadastro2.setBackground(new java.awt.Color(222, 222, 210));
        jPanelCadastro2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hobbies do Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jCheckBoxLeitura.setText("Leitura");

        jCheckBoxFutebol.setText("Futebol");

        jCheckBoxPescaria.setText("Pescaria");

        jCheckBoxDanca.setText("Dança");

        jCheckBoxGames.setText("Games");

        jCheckBoxCorrer.setText("Correr");

        jCheckBoxCozinhar.setText("Cozinhar");

        jCheckBoxMusica.setText("Musica");

        javax.swing.GroupLayout jPanelCadastro2Layout = new javax.swing.GroupLayout(jPanelCadastro2);
        jPanelCadastro2.setLayout(jPanelCadastro2Layout);
        jPanelCadastro2Layout.setHorizontalGroup(
            jPanelCadastro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastro2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelCadastro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxLeitura)
                    .addComponent(jCheckBoxGames))
                .addGap(163, 163, 163)
                .addGroup(jPanelCadastro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxFutebol)
                    .addComponent(jCheckBoxCorrer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addGroup(jPanelCadastro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxPescaria, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxCozinhar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(166, 166, 166)
                .addGroup(jPanelCadastro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxDanca)
                    .addComponent(jCheckBoxMusica))
                .addGap(27, 27, 27))
        );
        jPanelCadastro2Layout.setVerticalGroup(
            jPanelCadastro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastro2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxDanca)
                    .addComponent(jCheckBoxPescaria)
                    .addComponent(jCheckBoxFutebol)
                    .addComponent(jCheckBoxLeitura))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxGames)
                    .addComponent(jCheckBoxCorrer)
                    .addComponent(jCheckBoxCozinhar)
                    .addComponent(jCheckBoxMusica))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelCadastro2);
        jPanelCadastro2.setBounds(0, 250, 831, 100);

        jbTituloCad.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbTituloCad.setText("Tela de Cadastro de Clientes Pessoa Fisica ");
        getContentPane().add(jbTituloCad);
        jbTituloCad.setBounds(31, 12, 390, 24);

        jPanelBotoes.setBackground(new java.awt.Color(222, 222, 210));
        jPanelBotoes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btSalvar.setText("Salvar");
        btSalvar.setToolTipText("Use para Salvar os dados digitado.");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btConsultar.setText("Consultar");
        btConsultar.setToolTipText("Use para Consultar o dado em memoria.");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        btEditar.setText("Editar");
        btEditar.setToolTipText("Use para Editar o dado em memoria.");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.setToolTipText("Use para Excluir o dado em memoria.");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btSair.setText("Voltar");
        btSair.setToolTipText("Use para Voltar a tela principal.");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotoesLayout = new javax.swing.GroupLayout(jPanelBotoes);
        jPanelBotoes.setLayout(jPanelBotoesLayout);
        jPanelBotoesLayout.setHorizontalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 346, Short.MAX_VALUE)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelBotoesLayout.setVerticalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConsultar)
                    .addComponent(btExcluir)
                    .addComponent(btEditar)
                    .addComponent(btSalvar)
                    .addComponent(btSair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelBotoes);
        jPanelBotoes.setBounds(0, 360, 831, 50);

        jLabeImangemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/TalaFundoCad.jpg"))); // NOI18N
        getContentPane().add(jLabeImangemFundo);
        jLabeImangemFundo.setBounds(0, 0, 840, 400);

        setSize(new java.awt.Dimension(836, 416));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        //Codigo do botão Salva em memoria
        cliente.setNome(txNomeCad.getText());
    try {
        cliente.setNascimento(formato.parse(jFormattedTextFieldDtNascimento.getText()));
        } 
        catch (ParseException ex) {
            Logger.getLogger(FramePessoaFisica.class.getName()).log(Level.SEVERE, null, ex);
        }
        cliente.setEndereço(txNomeEnderecoCad.getText());
        cliente.setNumeroEndereço(Integer.parseInt(txNomeNumeroCad.getText())); //Use o Parse para fazer a conversão para Inteiro
        cliente.setCidade(txNomeCidadeCad.getText());
        cliente.setUf((String) cbEstado.getSelectedItem()); //Pega o item selecionado da Combo Box
        cliente.setCpf(jFormattedTextFieldCPF.getText());
        cliente.setSexo(jRadioButtonMasculinoCad.isSelected() == true?"Masculino":"Feminino"); //Tratamento do RadioButton
        cliente.setRenda(Float.parseFloat(jtRenda.getText()));
        cliente.setLeitura(jCheckBoxLeitura.isSelected());
        cliente.setFutebol(jCheckBoxFutebol.isSelected());
        cliente.setPescaria(jCheckBoxPescaria.isSelected());
        cliente.setDanca(jCheckBoxDanca.isSelected());
        cliente.setMusica(jCheckBoxMusica.isSelected());
        cliente.setVedeogame(jCheckBoxGames.isSelected());
        cliente.setCorrida(jCheckBoxCorrer.isSelected());
        cliente.setCozinhar(jCheckBoxCozinhar.isSelected());
        
        JOptionPane.showMessageDialog(null, "Dados inseridos com sucesso no objeto que está sendo instanciado na memória.");
        
        limparCampos();//Metodo para limpar todos os campos do frame
        
    }//GEN-LAST:event_btSalvarActionPerformed

    private void txNomeCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNomeCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNomeCadActionPerformed

    private void txNomeEnderecoCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNomeEnderecoCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNomeEnderecoCadActionPerformed

    private void txNomeCidadeCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNomeCidadeCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNomeCidadeCadActionPerformed

    private void jRadioButtonFemininoCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFemininoCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFemininoCadActionPerformed

    private void txNomeNumeroCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNomeNumeroCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNomeNumeroCadActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        // Metodo para recuperar o dado em memoria
        txNomeCad.setText(cliente.getNome());
        txNomeCad.setEnabled(false);//Trava o campo - Não Editavel
        
        jFormattedTextFieldDtNascimento.setText(formato.format(cliente.getNascimento()));
        jFormattedTextFieldDtNascimento.setEnabled(false);//Trava o campo - Não Editavel
        
        txNomeEnderecoCad.setText(cliente.getEndereço());
        txNomeEnderecoCad.setEnabled(false);//Trava o campo - Não Editavel
        
        txNomeNumeroCad.setText(String.valueOf(cliente.getNumeroEndereço()));
        txNomeNumeroCad.setEnabled(false);//Trava o campo - Não Editavel
                
        txNomeCidadeCad.setText(cliente.getCidade());
        txNomeCidadeCad.setEnabled(false);//Trava o campo - Não Editavel
                
        cbEstado.setSelectedItem(cliente.getUf());
        cbEstado.setEnabled(false);//Trava o campo - Não Editavel
                
        jFormattedTextFieldCPF.setText(cliente.getCpf());
        jFormattedTextFieldCPF.setEnabled(false);//Trava o campo - Não Editavel
                
        jRadioButtonMasculinoCad.setSelected("Masculino".equals(cliente.getSexo()));
        jRadioButtonMasculinoCad.setEnabled(false);//Trava o campo - Não Editavel
                
        jRadioButtonFemininoCad.setSelected("Feminino".equals(cliente.getSexo()));
        jRadioButtonFemininoCad.setEnabled(false);//Trava o campo - Não Editavel
                
        jtRenda.setText(String.valueOf(cliente.getRenda()));
        jtRenda.setEnabled(false);//Trava o campo - Não Editavel
                
        jCheckBoxLeitura.setSelected(cliente.isLeitura());
        jCheckBoxLeitura.setEnabled(false);//Trava o campo - Não Editavel
                
        jCheckBoxFutebol.setSelected(cliente.isFutebol());
        jCheckBoxFutebol.setEnabled(false);//Trava o campo - Não Editavel
                
        jCheckBoxPescaria.setSelected(cliente.isPescaria());
        jCheckBoxPescaria.setEnabled(false);//Trava o campo - Não Editavel
                
        jCheckBoxDanca.setSelected(cliente.isDanca());
        jCheckBoxDanca.setEnabled(false);//Trava o campo - Não Editavel
                
        jCheckBoxMusica.setSelected(cliente.isMusica());
        jCheckBoxMusica.setEnabled(false);//Trava o campo - Não Editavel
                
        jCheckBoxGames.setSelected(cliente.isVedeogame());
        jCheckBoxGames.setEnabled(false);//Trava o campo - Não Editavel
                
        jCheckBoxCorrer.setSelected(cliente.isCorrida());
        jCheckBoxCorrer.setEnabled(false);//Trava o campo - Não Editavel
                
        jCheckBoxCozinhar.setSelected(cliente.isCozinhar());
        jCheckBoxCozinhar.setEnabled(false);//Trava o campo - Não Editavel              
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        // Habilita a Edição dos campos
        txNomeCad.setEnabled(true);
        jFormattedTextFieldDtNascimento.setEnabled(true);
        txNomeEnderecoCad.setEnabled(true);
        txNomeNumeroCad.setEnabled(true);
        txNomeCidadeCad.setEnabled(true);
        cbEstado.setEnabled(true);
        jFormattedTextFieldCPF.setEnabled(true);
        jRadioButtonMasculinoCad.setEnabled(true);
        jRadioButtonFemininoCad.setEnabled(true);
        jtRenda.setEnabled(true);
        jCheckBoxLeitura.setEnabled(true);
        jCheckBoxFutebol.setEnabled(true);
        jCheckBoxPescaria.setEnabled(true);
        jCheckBoxDanca.setEnabled(true);
        jCheckBoxMusica.setEnabled(true);
        jCheckBoxGames.setEnabled(true);
        jCheckBoxCorrer.setEnabled(true);
        jCheckBoxCozinhar.setEnabled(true);        
    }//GEN-LAST:event_btEditarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // Exclui o objeto da memoria
        JOptionPane.showMessageDialog(null, "Deseja excluir esse cliente da memoria? ", "Exclusão do cliente", -1);
        limparCampos();
        cliente = null; //apaga o cliente da memoria
        JOptionPane.showMessageDialog(null,"Cliente excluido com sucesso!!!.");         
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
       this.dispose();        
    }//GEN-LAST:event_btSairActionPerformed

    //Metodo para limpar campos do frame
    public void limparCampos(){
        txNomeCad.setText("");
        jFormattedTextFieldDtNascimento.setText("");
        txNomeEnderecoCad.setText("");
        txNomeNumeroCad.setText("");
        txNomeCidadeCad.setText("");
        cbEstado.setSelectedIndex(0);
        jFormattedTextFieldCPF.setText("");
        buttonGroupoSexo.clearSelection();
        jtRenda.setText("");
        jCheckBoxLeitura.setSelected(false);
        jCheckBoxFutebol.setSelected(false);
        jCheckBoxPescaria.setSelected(false);
        jCheckBoxDanca.setSelected(false);
        jCheckBoxMusica.setSelected(false);
        jCheckBoxGames.setSelected(false);
        jCheckBoxCorrer.setSelected(false);
        jCheckBoxCozinhar.setSelected(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePessoaFisica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePessoaFisica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePessoaFisica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePessoaFisica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePessoaFisica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSalvar;
    private javax.swing.ButtonGroup buttonGroupoSexo;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JCheckBox jCheckBoxCorrer;
    private javax.swing.JCheckBox jCheckBoxCozinhar;
    private javax.swing.JCheckBox jCheckBoxDanca;
    private javax.swing.JCheckBox jCheckBoxFutebol;
    private javax.swing.JCheckBox jCheckBoxGames;
    private javax.swing.JCheckBox jCheckBoxLeitura;
    private javax.swing.JCheckBox jCheckBoxMusica;
    private javax.swing.JCheckBox jCheckBoxPescaria;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldDtNascimento;
    private javax.swing.JLabel jLabeImangemFundo;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelImagemFundoBordaPaineis;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JPanel jPanelCadastro2;
    private javax.swing.JPanel jPanelCadastroFisica;
    private javax.swing.JRadioButton jRadioButtonFemininoCad;
    private javax.swing.JRadioButton jRadioButtonMasculinoCad;
    private javax.swing.JLabel jbTituloCad;
    private javax.swing.JLabel jlRenda;
    private javax.swing.JTextField jtRenda;
    private javax.swing.JLabel lbCidadeCad;
    private javax.swing.JLabel lbDtNascimentoCad;
    private javax.swing.JLabel lbEnderecoCad;
    private javax.swing.JLabel lbEstadoCad;
    private javax.swing.JLabel lbNomeNomeCad;
    private javax.swing.JLabel lbSexoCad;
    private javax.swing.JTextField txNomeCad;
    private javax.swing.JTextField txNomeCidadeCad;
    private javax.swing.JTextField txNomeEnderecoCad;
    private javax.swing.JTextField txNomeNumeroCad;
    // End of variables declaration//GEN-END:variables

}
