/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JOptionPane;

/**
 *
 * @author aaa
 */
public class FrameAuxiliarBotoes extends javax.swing.JFrame {

    /**
     * Creates new form FrameAuxiliarBotoes
     */
    public FrameAuxiliarBotoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTelaBotoes = new javax.swing.JPanel();
        jLabelImgTelaBotoes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTreeMenuTelaInicial = new javax.swing.JTree();

        jPanelTelaBotoes.setLayout(null);

        jLabelImgTelaBotoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/TalaFundoBotoes.jpg"))); // NOI18N
        jPanelTelaBotoes.add(jLabelImgTelaBotoes);
        jLabelImgTelaBotoes.setBounds(-4, 0, 110, 457);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FATEC Linguagem de Programação III  - Sistema de Cadastro");
        setBackground(new java.awt.Color(222, 222, 210));
        setUndecorated(true);

        jTreeMenuTelaInicial.setBackground(new java.awt.Color(222, 222, 210));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Clientes");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Pessoa Fisica");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Pessoa Juridica");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Ferramentas");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Calculadora Swing");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode(".");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode(".");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode(".");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Fechar Menu");
        treeNode1.add(treeNode2);
        jTreeMenuTelaInicial.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTreeMenuTelaInicial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTreeMenuTelaInicial.setRootVisible(false);
        jTreeMenuTelaInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTreeMenuTelaInicialMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTreeMenuTelaInicial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setBounds(70, 135, 184, 459);
    }// </editor-fold>//GEN-END:initComponents

    private void jTreeMenuTelaInicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTreeMenuTelaInicialMouseClicked
        // Metodo de configuração do menu em arvore jTree
        String menu = jTreeMenuTelaInicial.getLastSelectedPathComponent().toString();
        
        if(menu.equals("Pessoa Fisica")){
            FramePessoaFisica frameCadastro = new FramePessoaFisica();
            frameCadastro.setVisible(true);
        }//fim do if Cad Pessoa Fisica
        if(menu.equals("Pessoa Juridica")){
            FramePessoaJuridica framePessoaJuridica = new FramePessoaJuridica();
            framePessoaJuridica.setVisible(true);
        }//fim do if Cad Pessoa Juridica
        if(menu.equals("Calculadora Swing")){
            FrameCalculadora frameCalculadora = new FrameCalculadora();
            frameCalculadora.setVisible(true);
        }//fim do if Calculadora Swing
        if(menu.equals("Fechar Menu")){
            dispose();
        }//fim do if Sair do Sistema
    }//GEN-LAST:event_jTreeMenuTelaInicialMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAuxiliarBotoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAuxiliarBotoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAuxiliarBotoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAuxiliarBotoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAuxiliarBotoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelImgTelaBotoes;
    private javax.swing.JPanel jPanelTelaBotoes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTreeMenuTelaInicial;
    // End of variables declaration//GEN-END:variables
}
