/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.View;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;


/**--------------------------------------------------------------------------
 * Sistema Guaxinim                                                         |
 * Descrição: Trabalho TG                                                   |
 * Sistema de inventario feito como conclusão do curso de ADS               |
 * na Fatec de Santana de Parnaiba.                                         |
 * @author Alessandro de Sousa da Silva  
 * @author Davi de Souza Silva|
 * Data: 08/03/2020                                                         |
/----------------------------------------------------------------------------
 */

public class frmCadFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form frmFornecedor
     */
    public frmCadFornecedor() {
        initComponents();
        //Adiciona Icone na barra de titulo
        URL iconeImagem = getClass().getResource("/imagens/63d15fc0193fd496d2484a161652f676.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(iconeImagem);
        this.setIconImage(iconeTitulo);
        //Fim - Adiciona Icone na barra de titulo
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldRazaoSocialCadFornecedor = new javax.swing.JTextField();
        jTextFieldCodCadFornecedor = new javax.swing.JTextField();
        jTextFieldCNPJCadFornecedor = new javax.swing.JTextField();
        jTextFieldEnderecoCadFornecedor = new javax.swing.JTextField();
        jTextFieldMunicipioCadFornecedor = new javax.swing.JTextField();
        jTextFieldBairroCadFornecedor = new javax.swing.JTextField();
        jTextFieldCEPCadFornecedor = new javax.swing.JTextField();
        jTextFieldTelefoneCadFornecedor = new javax.swing.JTextField();
        jTextFieldTelefone2CadFornecedor = new javax.swing.JTextField();
        jTextFieldEmailCadFornecedor = new javax.swing.JTextField();
        jTextFieldObservacaoCadFornecedor = new javax.swing.JTextField();
        jTextFieldNomeFantasiaCadFornecedor = new javax.swing.JTextField();
        jTextFieldContatoCadFornecedor = new javax.swing.JTextField();
        jTextFieldSiteCadFornecedor = new javax.swing.JTextField();
        jComboBoxEstadoCadFornecedor = new javax.swing.JComboBox<>();
        jComboBoxTipoCadFornecedor = new javax.swing.JComboBox<>();
        jLabelCadFornecedor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonSairCadFornecedor = new javax.swing.JButton();
        jButtonAnteriorCadFornecedor = new javax.swing.JButton();
        jButtonNovoCadFornecedor = new javax.swing.JButton();
        jButtonAlterarCadFornecedor = new javax.swing.JButton();
        jButtonSalvarCadFornecedor = new javax.swing.JButton();
        jButtonExcluirCadFornecedor = new javax.swing.JButton();
        jButtonProximoCadFornecedor = new javax.swing.JButton();
        jButtonCancelarCadFornecedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Guaxinim - Cadastro de Fornecedores");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Contato:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 390, 70, 17);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Observação:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 350, 100, 20);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Telefone:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 270, 76, 17);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Telefone2:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(410, 270, 80, 20);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("E-Mail:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 310, 60, 17);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Estado:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(490, 230, 60, 20);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Tipo Fornec:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(480, 110, 150, 17);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText(" Site:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(90, 430, 40, 17);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Municipio:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 230, 80, 17);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Endereço:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(60, 190, 90, 17);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("CNPJ:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(90, 150, 70, 17);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("Razão Social:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(40, 70, 100, 17);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("CEP:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(560, 150, 36, 17);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("Codigo do Fornecedor:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(430, 30, 170, 20);

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText(" Bairro:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(460, 190, 70, 17);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setText("Nome Fantasia:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(30, 110, 120, 17);
        jPanel1.add(jTextFieldRazaoSocialCadFornecedor);
        jTextFieldRazaoSocialCadFornecedor.setBounds(140, 60, 610, 30);

        jTextFieldCodCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodCadFornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCodCadFornecedor);
        jTextFieldCodCadFornecedor.setBounds(600, 20, 150, 30);

        jTextFieldCNPJCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCNPJCadFornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCNPJCadFornecedor);
        jTextFieldCNPJCadFornecedor.setBounds(140, 140, 330, 30);

        jTextFieldEnderecoCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnderecoCadFornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldEnderecoCadFornecedor);
        jTextFieldEnderecoCadFornecedor.setBounds(140, 180, 320, 30);

        jTextFieldMunicipioCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMunicipioCadFornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldMunicipioCadFornecedor);
        jTextFieldMunicipioCadFornecedor.setBounds(140, 220, 330, 30);

        jTextFieldBairroCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBairroCadFornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldBairroCadFornecedor);
        jTextFieldBairroCadFornecedor.setBounds(520, 180, 230, 30);

        jTextFieldCEPCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCEPCadFornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCEPCadFornecedor);
        jTextFieldCEPCadFornecedor.setBounds(600, 140, 150, 30);

        jTextFieldTelefoneCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefoneCadFornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTelefoneCadFornecedor);
        jTextFieldTelefoneCadFornecedor.setBounds(140, 260, 260, 30);

        jTextFieldTelefone2CadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefone2CadFornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTelefone2CadFornecedor);
        jTextFieldTelefone2CadFornecedor.setBounds(490, 260, 260, 30);

        jTextFieldEmailCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailCadFornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldEmailCadFornecedor);
        jTextFieldEmailCadFornecedor.setBounds(140, 300, 610, 30);

        jTextFieldObservacaoCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldObservacaoCadFornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldObservacaoCadFornecedor);
        jTextFieldObservacaoCadFornecedor.setBounds(140, 340, 610, 30);

        jTextFieldNomeFantasiaCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeFantasiaCadFornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNomeFantasiaCadFornecedor);
        jTextFieldNomeFantasiaCadFornecedor.setBounds(140, 100, 330, 30);

        jTextFieldContatoCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContatoCadFornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldContatoCadFornecedor);
        jTextFieldContatoCadFornecedor.setBounds(140, 380, 610, 30);

        jTextFieldSiteCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSiteCadFornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldSiteCadFornecedor);
        jTextFieldSiteCadFornecedor.setBounds(140, 420, 610, 30);

        jComboBoxEstadoCadFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "AC - Acre", "AL - Alagoas", "AP - Amapá", "AM - Amazonas", "BA - Bahia ", "CE - Ceará", "DF - Distrito Federal", "ES - Espírito Santo", "GO - Goiás", "MA - Maranhão", "MT - Mato Grosso", "MS - Mato Grosso do Sul", "MG - Minas Gerais", "PA - Pará", "PB - Paraíba", "PR - Paraná", "PE - Pernambuco", "PI - Piauí", "RR - Roraima", "RO - Rondônia", "RJ - Rio de Janeiro", "RN - Rio Grande do Norte", "RS - Rio Grande do Sul", "SC - Santa Catarina", "SP - São Paulo", "SE - Sergipe", "TO - Tocantins" }));
        jPanel1.add(jComboBoxEstadoCadFornecedor);
        jComboBoxEstadoCadFornecedor.setBounds(550, 220, 200, 30);

        jComboBoxTipoCadFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione..." }));
        jComboBoxTipoCadFornecedor.setToolTipText("Selecione o Tipo de Fornecedor");
        jPanel1.add(jComboBoxTipoCadFornecedor);
        jComboBoxTipoCadFornecedor.setBounds(570, 100, 180, 30);

        jLabelCadFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cadastros.jpg"))); // NOI18N
        jPanel1.add(jLabelCadFornecedor);
        jLabelCadFornecedor.setBounds(10, 10, 770, 470);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Fornecedores");

        jButtonSairCadFornecedor.setText("Voltar");
        jButtonSairCadFornecedor.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonSairCadFornecedor.setMinimumSize(new java.awt.Dimension(82, 26));
        jButtonSairCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairCadFornecedorActionPerformed(evt);
            }
        });

        jButtonAnteriorCadFornecedor.setText("Anterior");
        jButtonAnteriorCadFornecedor.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonAnteriorCadFornecedor.setMinimumSize(new java.awt.Dimension(82, 26));

        jButtonNovoCadFornecedor.setText("Novo");
        jButtonNovoCadFornecedor.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonNovoCadFornecedor.setMinimumSize(new java.awt.Dimension(82, 26));
        jButtonNovoCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoCadFornecedorActionPerformed(evt);
            }
        });

        jButtonAlterarCadFornecedor.setText("Alterar");
        jButtonAlterarCadFornecedor.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonAlterarCadFornecedor.setMinimumSize(new java.awt.Dimension(82, 26));

        jButtonSalvarCadFornecedor.setText("Salvar");
        jButtonSalvarCadFornecedor.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonSalvarCadFornecedor.setMinimumSize(new java.awt.Dimension(82, 26));

        jButtonExcluirCadFornecedor.setText("Excluir");
        jButtonExcluirCadFornecedor.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonExcluirCadFornecedor.setMinimumSize(new java.awt.Dimension(82, 26));

        jButtonProximoCadFornecedor.setText("Proximo");

        jButtonCancelarCadFornecedor.setText("Cancelar");
        jButtonCancelarCadFornecedor.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonCancelarCadFornecedor.setMinimumSize(new java.awt.Dimension(82, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAnteriorCadFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNovoCadFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAlterarCadFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvarCadFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelarCadFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluirCadFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonProximoCadFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(jButtonSairCadFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSairCadFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAnteriorCadFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNovoCadFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlterarCadFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvarCadFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluirCadFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProximoCadFornecedor)
                    .addComponent(jButtonCancelarCadFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(796, 571));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodCadFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodCadFornecedorActionPerformed

    private void jTextFieldEnderecoCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoCadFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnderecoCadFornecedorActionPerformed

    private void jTextFieldEmailCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailCadFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailCadFornecedorActionPerformed

    private void jTextFieldCNPJCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCNPJCadFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCNPJCadFornecedorActionPerformed

    private void jTextFieldMunicipioCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMunicipioCadFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMunicipioCadFornecedorActionPerformed

    private void jTextFieldTelefone2CadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefone2CadFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefone2CadFornecedorActionPerformed

    private void jTextFieldCEPCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCEPCadFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCEPCadFornecedorActionPerformed

    private void jTextFieldContatoCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContatoCadFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContatoCadFornecedorActionPerformed

    private void jTextFieldSiteCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSiteCadFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSiteCadFornecedorActionPerformed

    private void jTextFieldObservacaoCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldObservacaoCadFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldObservacaoCadFornecedorActionPerformed

    private void jTextFieldTelefoneCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefoneCadFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefoneCadFornecedorActionPerformed

    private void jButtonSairCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairCadFornecedorActionPerformed
        // TODO add your handling code here:
        this.dispose(); //fecha somente o jFrame do frmCadFornecedor
         
    }//GEN-LAST:event_jButtonSairCadFornecedorActionPerformed

    private void jTextFieldBairroCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBairroCadFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBairroCadFornecedorActionPerformed

    private void jTextFieldNomeFantasiaCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeFantasiaCadFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeFantasiaCadFornecedorActionPerformed

    private void jButtonNovoCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoCadFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNovoCadFornecedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCadFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarCadFornecedor;
    private javax.swing.JButton jButtonAnteriorCadFornecedor;
    private javax.swing.JButton jButtonCancelarCadFornecedor;
    private javax.swing.JButton jButtonExcluirCadFornecedor;
    private javax.swing.JButton jButtonNovoCadFornecedor;
    private javax.swing.JButton jButtonProximoCadFornecedor;
    private javax.swing.JButton jButtonSairCadFornecedor;
    private javax.swing.JButton jButtonSalvarCadFornecedor;
    private javax.swing.JComboBox<String> jComboBoxEstadoCadFornecedor;
    private javax.swing.JComboBox<String> jComboBoxTipoCadFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCadFornecedor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldBairroCadFornecedor;
    private javax.swing.JTextField jTextFieldCEPCadFornecedor;
    private javax.swing.JTextField jTextFieldCNPJCadFornecedor;
    private javax.swing.JTextField jTextFieldCodCadFornecedor;
    private javax.swing.JTextField jTextFieldContatoCadFornecedor;
    private javax.swing.JTextField jTextFieldEmailCadFornecedor;
    private javax.swing.JTextField jTextFieldEnderecoCadFornecedor;
    private javax.swing.JTextField jTextFieldMunicipioCadFornecedor;
    private javax.swing.JTextField jTextFieldNomeFantasiaCadFornecedor;
    private javax.swing.JTextField jTextFieldObservacaoCadFornecedor;
    private javax.swing.JTextField jTextFieldRazaoSocialCadFornecedor;
    private javax.swing.JTextField jTextFieldSiteCadFornecedor;
    private javax.swing.JTextField jTextFieldTelefone2CadFornecedor;
    private javax.swing.JTextField jTextFieldTelefoneCadFornecedor;
    // End of variables declaration//GEN-END:variables
}
