/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.View;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;


/**--------------------------------------------------------------------------
 * Sistema Guaxinim                                                         |
 * Descrição: Trabalho TG                                                   |
 * Sistema de inventario feito como conclusão do curso de ADS               |
 * na Fatec de Santana de Parnaiba.                                         |
 * @author Alessandro de Sousa da Silva                                     |
 * @author Davi de Souza Silva                                              |
 * Data: 08/03/2020                                                         |
/----------------------------------------------------------------------------
 */

public class frmCadTrocaSenha extends javax.swing.JFrame {

    /**
     * Creates new form frmFornecedor
     */
    public frmCadTrocaSenha() {
        initComponents();
        //Adiciona Icone na barra de titulo
        URL iconeImagem = getClass().getResource("/imagens/63d15fc0193fd496d2484a161652f676.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(iconeImagem);
        this.setIconImage(iconeTitulo);
        //Fim - Adiciona Icone na barra de titulo
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldCodUsrCadTrocaSenha = new javax.swing.JTextField();
        jTextFieldDtExpiraCadTrocaSenha = new javax.swing.JTextField();
        jTextFieldNomeCadTrocaSenha = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldDataCadTrocaSenha = new javax.swing.JTextField();
        jTextFieldSenhaAtualCadTrocaSenha = new javax.swing.JTextField();
        jTextFieldConfirmaSenhaCadTrocaSenha = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldSenhaCadTrocaSenha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonSairCadTrocaSenha = new javax.swing.JButton();
        jButtonAnteriorCadTrocaSenha = new javax.swing.JButton();
        jButtonAlterarCadTrocaSenha = new javax.swing.JButton();
        jButtonCancelarCadTrocaSenha = new javax.swing.JButton();
        jButtonProximoCadTrocaSenha = new javax.swing.JButton();
        jButtonNovoCadTrocaSenha1 = new javax.swing.JButton();
        jButtonSalvarCadTrocaSenha2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Guaxinim - Cadastro e Troca da Senha");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Nome:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(310, 70, 110, 17);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Senha Atual:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(100, 110, 120, 17);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("Cod. Usuario:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(30, 70, 120, 17);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("A Senha expira em:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(460, 30, 140, 20);
        jPanel1.add(jTextFieldCodUsrCadTrocaSenha);
        jTextFieldCodUsrCadTrocaSenha.setBounds(150, 60, 150, 30);

        jTextFieldDtExpiraCadTrocaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDtExpiraCadTrocaSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldDtExpiraCadTrocaSenha);
        jTextFieldDtExpiraCadTrocaSenha.setBounds(600, 20, 150, 30);

        jTextFieldNomeCadTrocaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeCadTrocaSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNomeCadTrocaSenha);
        jTextFieldNomeCadTrocaSenha.setBounds(360, 60, 390, 30);

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("Data Atual:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(30, 30, 90, 20);

        jTextFieldDataCadTrocaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataCadTrocaSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldDataCadTrocaSenha);
        jTextFieldDataCadTrocaSenha.setBounds(150, 20, 150, 30);

        jTextFieldSenhaAtualCadTrocaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSenhaAtualCadTrocaSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldSenhaAtualCadTrocaSenha);
        jTextFieldSenhaAtualCadTrocaSenha.setBounds(200, 100, 370, 30);

        jTextFieldConfirmaSenhaCadTrocaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldConfirmaSenhaCadTrocaSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldConfirmaSenhaCadTrocaSenha);
        jTextFieldConfirmaSenhaCadTrocaSenha.setBounds(200, 180, 370, 30);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("Confirmação da Senha:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(30, 190, 170, 17);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setText("Nova Senha:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(100, 150, 120, 17);

        jTextFieldSenhaCadTrocaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSenhaCadTrocaSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldSenhaCadTrocaSenha);
        jTextFieldSenhaCadTrocaSenha.setBounds(200, 140, 370, 30);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro e Troca da Senha");

        jButtonSairCadTrocaSenha.setText("Voltar");
        jButtonSairCadTrocaSenha.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonSairCadTrocaSenha.setMinimumSize(new java.awt.Dimension(82, 26));
        jButtonSairCadTrocaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairCadTrocaSenhaActionPerformed(evt);
            }
        });

        jButtonAnteriorCadTrocaSenha.setText("Anterior");
        jButtonAnteriorCadTrocaSenha.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonAnteriorCadTrocaSenha.setMinimumSize(new java.awt.Dimension(82, 26));

        jButtonAlterarCadTrocaSenha.setText("Alterar");
        jButtonAlterarCadTrocaSenha.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonAlterarCadTrocaSenha.setMinimumSize(new java.awt.Dimension(82, 26));

        jButtonCancelarCadTrocaSenha.setText("Cancelar");
        jButtonCancelarCadTrocaSenha.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonCancelarCadTrocaSenha.setMinimumSize(new java.awt.Dimension(82, 26));

        jButtonProximoCadTrocaSenha.setText("Proximo");

        jButtonNovoCadTrocaSenha1.setText("Novo");
        jButtonNovoCadTrocaSenha1.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonNovoCadTrocaSenha1.setMinimumSize(new java.awt.Dimension(82, 26));

        jButtonSalvarCadTrocaSenha2.setText("Salvar");
        jButtonSalvarCadTrocaSenha2.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonSalvarCadTrocaSenha2.setMinimumSize(new java.awt.Dimension(82, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAnteriorCadTrocaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNovoCadTrocaSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAlterarCadTrocaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvarCadTrocaSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelarCadTrocaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonProximoCadTrocaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                        .addComponent(jButtonSairCadTrocaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSairCadTrocaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAnteriorCadTrocaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlterarCadTrocaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelarCadTrocaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProximoCadTrocaSenha)
                    .addComponent(jButtonNovoCadTrocaSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvarCadTrocaSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(796, 337));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDtExpiraCadTrocaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDtExpiraCadTrocaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDtExpiraCadTrocaSenhaActionPerformed

    private void jTextFieldNomeCadTrocaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeCadTrocaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeCadTrocaSenhaActionPerformed

    private void jButtonSairCadTrocaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairCadTrocaSenhaActionPerformed
        // TODO add your handling code here:
        this.dispose(); //fecha somente o jFrame do frmCadUsuario
         
    }//GEN-LAST:event_jButtonSairCadTrocaSenhaActionPerformed

    private void jTextFieldDataCadTrocaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataCadTrocaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataCadTrocaSenhaActionPerformed

    private void jTextFieldSenhaAtualCadTrocaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSenhaAtualCadTrocaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSenhaAtualCadTrocaSenhaActionPerformed

    private void jTextFieldConfirmaSenhaCadTrocaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldConfirmaSenhaCadTrocaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldConfirmaSenhaCadTrocaSenhaActionPerformed

    private void jTextFieldSenhaCadTrocaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSenhaCadTrocaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSenhaCadTrocaSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCadTrocaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCadTrocaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCadTrocaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCadTrocaSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCadTrocaSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarCadTrocaSenha;
    private javax.swing.JButton jButtonAnteriorCadTrocaSenha;
    private javax.swing.JButton jButtonCancelarCadTrocaSenha;
    private javax.swing.JButton jButtonNovoCadTrocaSenha1;
    private javax.swing.JButton jButtonProximoCadTrocaSenha;
    private javax.swing.JButton jButtonSairCadTrocaSenha;
    private javax.swing.JButton jButtonSalvarCadTrocaSenha2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCodUsrCadTrocaSenha;
    private javax.swing.JTextField jTextFieldConfirmaSenhaCadTrocaSenha;
    private javax.swing.JTextField jTextFieldDataCadTrocaSenha;
    private javax.swing.JTextField jTextFieldDtExpiraCadTrocaSenha;
    private javax.swing.JTextField jTextFieldNomeCadTrocaSenha;
    private javax.swing.JTextField jTextFieldSenhaAtualCadTrocaSenha;
    private javax.swing.JTextField jTextFieldSenhaCadTrocaSenha;
    // End of variables declaration//GEN-END:variables
}
