/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.View;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;


/**--------------------------------------------------------------------------
 * Sistema Guaxinim                                                         |
 * Descrição: Trabalho TG                                                   |
 * Sistema de inventario feito como conclusão do curso de ADS               |
 * na Fatec de Santana de Parnaiba.                                         |
 * @author Alessandro de Sousa da Silva  
 * @author Davi de Souza Silva|
 * Data: 08/03/2020                                                         |
/----------------------------------------------------------------------------
 */

public class frmCadProduto extends javax.swing.JFrame {

    /**
     * Creates new form frmFornecedor
     */
    public frmCadProduto() {
        initComponents();
        //Adiciona Icone na barra de titulo
        URL iconeImagem = getClass().getResource("/imagens/63d15fc0193fd496d2484a161652f676.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(iconeImagem);
        this.setIconImage(iconeTitulo);
        //Fim - Adiciona Icone na barra de titulo
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabelColarIMGCadProduto = new javax.swing.JLabel();
        jTextFieldNomeCadProduto = new javax.swing.JTextField();
        jTextFieldCodigoInternoCadProduto = new javax.swing.JTextField();
        jTextFieldDescricaoCadProduto = new javax.swing.JTextField();
        jTextFieldNumAtivoCadProduto = new javax.swing.JTextField();
        jTextFieldNumSerieCadProduto = new javax.swing.JTextField();
        jTextFieldEnderecoCadProduto = new javax.swing.JTextField();
        jTextFieldObservacaoCadProduto = new javax.swing.JTextField();
        jTextFieldCodBarraCadProduto = new javax.swing.JTextField();
        jComboBoxStatusCadProduto = new javax.swing.JComboBox<>();
        jComboBoxCadastradoPorCadProduto = new javax.swing.JComboBox<>();
        jComboBoxTipoProdCadProduto = new javax.swing.JComboBox<>();
        jComboBoxCategoriaCadProduto = new javax.swing.JComboBox<>();
        jButtonAdicionaIMGCadProduto = new javax.swing.JButton();
        jButtonExcluirIMGCadProduto = new javax.swing.JButton();
        jTextFieldCodigoCadProduto = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonSairCadProduto = new javax.swing.JButton();
        jButtonAnteriorCadProduto = new javax.swing.JButton();
        jButtonNovoCadProduto = new javax.swing.JButton();
        jButtonAlterarCadProduto = new javax.swing.JButton();
        jButtonCancelarCadProduto = new javax.swing.JButton();
        jButtonExcluirCadProduto = new javax.swing.JButton();
        jButtonProximoCadProduto = new javax.swing.JButton();
        jButtonSalvarCadProduto1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Guaxinim - Cadastro de Produto");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Observação:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 390, 100, 20);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Endereço:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 310, 81, 17);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Tipo do Produto:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 190, 120, 17);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Status do Produto:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(490, 430, 140, 17);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Num. de Serie:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 270, 140, 17);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Num. Ativo:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 230, 110, 17);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Descrição  Prod:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 110, 120, 17);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("Nome do Produto:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 70, 160, 17);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("Imagem do Produto:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(530, 150, 280, 17);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("Codigo do Produto (Interno):");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(520, 30, 210, 20);

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("Cod. de Barra:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(20, 350, 120, 17);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setText("Categoria:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(20, 150, 130, 17);

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setText("Cadastrado Por:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(20, 430, 120, 17);

        jLabelColarIMGCadProduto.setBackground(new java.awt.Color(255, 255, 255));
        jLabelColarIMGCadProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cole sua imagem aqui.png"))); // NOI18N
        jPanel1.add(jLabelColarIMGCadProduto);
        jLabelColarIMGCadProduto.setBounds(530, 180, 380, 150);
        jPanel1.add(jTextFieldNomeCadProduto);
        jTextFieldNomeCadProduto.setBounds(150, 60, 760, 30);

        jTextFieldCodigoInternoCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoInternoCadProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCodigoInternoCadProduto);
        jTextFieldCodigoInternoCadProduto.setBounds(730, 20, 180, 30);

        jTextFieldDescricaoCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescricaoCadProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldDescricaoCadProduto);
        jTextFieldDescricaoCadProduto.setBounds(150, 100, 600, 30);

        jTextFieldNumAtivoCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumAtivoCadProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNumAtivoCadProduto);
        jTextFieldNumAtivoCadProduto.setBounds(150, 220, 330, 30);

        jTextFieldNumSerieCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumSerieCadProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNumSerieCadProduto);
        jTextFieldNumSerieCadProduto.setBounds(150, 260, 330, 30);

        jTextFieldEnderecoCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnderecoCadProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldEnderecoCadProduto);
        jTextFieldEnderecoCadProduto.setBounds(150, 300, 330, 30);

        jTextFieldObservacaoCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldObservacaoCadProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldObservacaoCadProduto);
        jTextFieldObservacaoCadProduto.setBounds(150, 380, 760, 30);
        jPanel1.add(jTextFieldCodBarraCadProduto);
        jTextFieldCodBarraCadProduto.setBounds(150, 340, 330, 30);

        jComboBoxStatusCadProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha a Opção...", "Ativo", "Inativo", "Bloqueado", "Para Doação" }));
        jComboBoxStatusCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStatusCadProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxStatusCadProduto);
        jComboBoxStatusCadProduto.setBounds(630, 420, 280, 30);

        jComboBoxCadastradoPorCadProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha a Opção...", " " }));
        jPanel1.add(jComboBoxCadastradoPorCadProduto);
        jComboBoxCadastradoPorCadProduto.setBounds(150, 420, 330, 30);

        jComboBoxTipoProdCadProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha a Opção...", " " }));
        jComboBoxTipoProdCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoProdCadProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxTipoProdCadProduto);
        jComboBoxTipoProdCadProduto.setBounds(150, 180, 330, 30);

        jComboBoxCategoriaCadProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha a Opção...", " " }));
        jPanel1.add(jComboBoxCategoriaCadProduto);
        jComboBoxCategoriaCadProduto.setBounds(150, 140, 330, 30);

        jButtonAdicionaIMGCadProduto.setText("Adicionar");
        jPanel1.add(jButtonAdicionaIMGCadProduto);
        jButtonAdicionaIMGCadProduto.setBounds(530, 340, 100, 35);

        jButtonExcluirIMGCadProduto.setText("Excluir");
        jPanel1.add(jButtonExcluirIMGCadProduto);
        jButtonExcluirIMGCadProduto.setBounds(650, 340, 100, 35);

        jTextFieldCodigoCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoCadProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCodigoCadProduto);
        jTextFieldCodigoCadProduto.setBounds(150, 20, 150, 30);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setText("Codigo do Produto:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(10, 30, 140, 20);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Produto");

        jButtonSairCadProduto.setText("Voltar");
        jButtonSairCadProduto.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonSairCadProduto.setMinimumSize(new java.awt.Dimension(82, 26));
        jButtonSairCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairCadProdutoActionPerformed(evt);
            }
        });

        jButtonAnteriorCadProduto.setText("Anterior");
        jButtonAnteriorCadProduto.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonAnteriorCadProduto.setMinimumSize(new java.awt.Dimension(82, 26));

        jButtonNovoCadProduto.setText("Novo");
        jButtonNovoCadProduto.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonNovoCadProduto.setMinimumSize(new java.awt.Dimension(82, 26));

        jButtonAlterarCadProduto.setText("Alterar");
        jButtonAlterarCadProduto.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonAlterarCadProduto.setMinimumSize(new java.awt.Dimension(82, 26));

        jButtonCancelarCadProduto.setText("Cancelar");
        jButtonCancelarCadProduto.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonCancelarCadProduto.setMinimumSize(new java.awt.Dimension(82, 26));

        jButtonExcluirCadProduto.setText("Excluir");
        jButtonExcluirCadProduto.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonExcluirCadProduto.setMinimumSize(new java.awt.Dimension(82, 26));

        jButtonProximoCadProduto.setText("Proximo");

        jButtonSalvarCadProduto1.setText("Salvar");
        jButtonSalvarCadProduto1.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonSalvarCadProduto1.setMinimumSize(new java.awt.Dimension(82, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 726, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAnteriorCadProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNovoCadProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAlterarCadProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvarCadProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelarCadProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluirCadProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonProximoCadProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                        .addComponent(jButtonSairCadProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSairCadProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAnteriorCadProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNovoCadProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlterarCadProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelarCadProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluirCadProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProximoCadProduto)
                    .addComponent(jButtonSalvarCadProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        setBounds(300, 87, 940, 564);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairCadProdutoActionPerformed
        // TODO add your handling code here:
        this.dispose(); //fecha somente o jFrame do frmCadUsuario
         
    }//GEN-LAST:event_jButtonSairCadProdutoActionPerformed

    private void jTextFieldCodigoCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoCadProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoCadProdutoActionPerformed

    private void jTextFieldObservacaoCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldObservacaoCadProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldObservacaoCadProdutoActionPerformed

    private void jTextFieldEnderecoCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoCadProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnderecoCadProdutoActionPerformed

    private void jTextFieldNumSerieCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumSerieCadProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumSerieCadProdutoActionPerformed

    private void jTextFieldNumAtivoCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumAtivoCadProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumAtivoCadProdutoActionPerformed

    private void jTextFieldDescricaoCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoCadProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescricaoCadProdutoActionPerformed

    private void jTextFieldCodigoInternoCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoInternoCadProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoInternoCadProdutoActionPerformed

    private void jComboBoxStatusCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStatusCadProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxStatusCadProdutoActionPerformed

    private void jComboBoxTipoProdCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoProdCadProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoProdCadProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCadProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionaIMGCadProduto;
    private javax.swing.JButton jButtonAlterarCadProduto;
    private javax.swing.JButton jButtonAnteriorCadProduto;
    private javax.swing.JButton jButtonCancelarCadProduto;
    private javax.swing.JButton jButtonExcluirCadProduto;
    private javax.swing.JButton jButtonExcluirIMGCadProduto;
    private javax.swing.JButton jButtonNovoCadProduto;
    private javax.swing.JButton jButtonProximoCadProduto;
    private javax.swing.JButton jButtonSairCadProduto;
    private javax.swing.JButton jButtonSalvarCadProduto1;
    private javax.swing.JComboBox<String> jComboBoxCadastradoPorCadProduto;
    private javax.swing.JComboBox<String> jComboBoxCategoriaCadProduto;
    private javax.swing.JComboBox<String> jComboBoxStatusCadProduto;
    private javax.swing.JComboBox<String> jComboBoxTipoProdCadProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelColarIMGCadProduto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCodBarraCadProduto;
    private javax.swing.JTextField jTextFieldCodigoCadProduto;
    private javax.swing.JTextField jTextFieldCodigoInternoCadProduto;
    private javax.swing.JTextField jTextFieldDescricaoCadProduto;
    private javax.swing.JTextField jTextFieldEnderecoCadProduto;
    private javax.swing.JTextField jTextFieldNomeCadProduto;
    private javax.swing.JTextField jTextFieldNumAtivoCadProduto;
    private javax.swing.JTextField jTextFieldNumSerieCadProduto;
    private javax.swing.JTextField jTextFieldObservacaoCadProduto;
    // End of variables declaration//GEN-END:variables
}
