/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.View;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;


/**--------------------------------------------------------------------------
 * Sistema Guaxinim                                                         |
 * Descrição: Trabalho TG                                                   |
 * Sistema de inventario feito como conclusão do curso de ADS               |
 * na Fatec de Santana de Parnaiba.                                         |
 * @author Alessandro de Sousa da Silva                                     |
 * @author Davi de Souza Silva                                              |
 * Data: 08/03/2020                                                         |
/----------------------------------------------------------------------------
 */

public class frmInventario extends javax.swing.JFrame {

    /**
     * Creates new form frmFornecedor
     */
    public frmInventario() {
        initComponents();
        //Adiciona Icone na barra de titulo
        URL iconeImagem = getClass().getResource("/imagens/63d15fc0193fd496d2484a161652f676.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(iconeImagem);
        this.setIconImage(iconeTitulo);
        //Fim - Adiciona Icone na barra de titulo
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldCodigoInternoCadProduto = new javax.swing.JTextField();
        jTextFieldDescricaoCadProduto = new javax.swing.JTextField();
        jTextFieldObservacaoCadProduto = new javax.swing.JTextField();
        jComboBoxCadastradoPorCadProduto = new javax.swing.JComboBox<>();
        jTextFieldCodigoCadProduto = new javax.swing.JTextField();
        jTextFieldCodigoInternoCadProduto1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldCodigoInternoCadProduto2 = new javax.swing.JTextField();
        jTabbedPaneInventario = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonSairInventario = new javax.swing.JButton();
        jButtonAlterarInventario = new javax.swing.JButton();
        jButtonCancelarInventario = new javax.swing.JButton();
        jButtonExcluirInventario = new javax.swing.JButton();
        jButtonSalvlarInventario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Guaxinim - Inventario");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Observação:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 410, 100, 20);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Data:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(560, 450, 60, 17);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Descrição do Inventário:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 100, 180, 17);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("Codigo do Inventário:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(30, 20, 160, 20);

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setText("Inventariado Por:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(20, 450, 140, 17);

        jTextFieldCodigoInternoCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoInternoCadProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCodigoInternoCadProduto);
        jTextFieldCodigoInternoCadProduto.setBounds(610, 440, 140, 30);

        jTextFieldDescricaoCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescricaoCadProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldDescricaoCadProduto);
        jTextFieldDescricaoCadProduto.setBounds(190, 90, 720, 30);

        jTextFieldObservacaoCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldObservacaoCadProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldObservacaoCadProduto);
        jTextFieldObservacaoCadProduto.setBounds(150, 400, 760, 30);

        jComboBoxCadastradoPorCadProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha a Opção...", " " }));
        jPanel1.add(jComboBoxCadastradoPorCadProduto);
        jComboBoxCadastradoPorCadProduto.setBounds(150, 440, 250, 30);

        jTextFieldCodigoCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoCadProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCodigoCadProduto);
        jTextFieldCodigoCadProduto.setBounds(190, 50, 150, 30);

        jTextFieldCodigoInternoCadProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoInternoCadProduto1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCodigoInternoCadProduto1);
        jTextFieldCodigoInternoCadProduto1.setBounds(190, 10, 150, 30);

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setText("Hora:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(760, 450, 40, 17);

        jTextFieldCodigoInternoCadProduto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoInternoCadProduto2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCodigoInternoCadProduto2);
        jTextFieldCodigoInternoCadProduto2.setBounds(800, 440, 110, 30);

        jTabbedPaneInventario.setBackground(new java.awt.Color(102, 102, 102));
        jTabbedPaneInventario.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhe - Inventario"));
        jTabbedPaneInventario.addTab("Ajuste do Inventário", jScrollPane1);

        jPanel1.add(jTabbedPaneInventario);
        jTabbedPaneInventario.setBounds(10, 130, 900, 260);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setText("Data de Execução:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(50, 60, 140, 20);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Controle de Inventario");

        jButtonSairInventario.setText("Voltar");
        jButtonSairInventario.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonSairInventario.setMinimumSize(new java.awt.Dimension(82, 26));
        jButtonSairInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairInventarioActionPerformed(evt);
            }
        });

        jButtonAlterarInventario.setText("Alterar");
        jButtonAlterarInventario.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonAlterarInventario.setMinimumSize(new java.awt.Dimension(82, 26));

        jButtonCancelarInventario.setText("Cancelar");
        jButtonCancelarInventario.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonCancelarInventario.setMinimumSize(new java.awt.Dimension(82, 26));

        jButtonExcluirInventario.setText("Excluir");
        jButtonExcluirInventario.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonExcluirInventario.setMinimumSize(new java.awt.Dimension(82, 26));

        jButtonSalvlarInventario.setText("Salvar");
        jButtonSalvlarInventario.setMaximumSize(new java.awt.Dimension(82, 26));
        jButtonSalvlarInventario.setMinimumSize(new java.awt.Dimension(82, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAlterarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvlarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluirInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 341, Short.MAX_VALUE)
                        .addComponent(jButtonSairInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAlterarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCancelarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonExcluirInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSalvlarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonSairInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setBounds(300, 87, 940, 564);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairInventarioActionPerformed
        // TODO add your handling code here:
        this.dispose(); //fecha somente o jFrame do frmCadUsuario
         
    }//GEN-LAST:event_jButtonSairInventarioActionPerformed

    private void jTextFieldCodigoInternoCadProduto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoInternoCadProduto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoInternoCadProduto2ActionPerformed

    private void jTextFieldCodigoInternoCadProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoInternoCadProduto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoInternoCadProduto1ActionPerformed

    private void jTextFieldCodigoCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoCadProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoCadProdutoActionPerformed

    private void jTextFieldObservacaoCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldObservacaoCadProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldObservacaoCadProdutoActionPerformed

    private void jTextFieldDescricaoCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoCadProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescricaoCadProdutoActionPerformed

    private void jTextFieldCodigoInternoCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoInternoCadProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoInternoCadProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarInventario;
    private javax.swing.JButton jButtonCancelarInventario;
    private javax.swing.JButton jButtonExcluirInventario;
    private javax.swing.JButton jButtonSairInventario;
    private javax.swing.JButton jButtonSalvlarInventario;
    private javax.swing.JComboBox<String> jComboBoxCadastradoPorCadProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneInventario;
    private javax.swing.JTextField jTextFieldCodigoCadProduto;
    private javax.swing.JTextField jTextFieldCodigoInternoCadProduto;
    private javax.swing.JTextField jTextFieldCodigoInternoCadProduto1;
    private javax.swing.JTextField jTextFieldCodigoInternoCadProduto2;
    private javax.swing.JTextField jTextFieldDescricaoCadProduto;
    private javax.swing.JTextField jTextFieldObservacaoCadProduto;
    // End of variables declaration//GEN-END:variables
}
